################################################################
## Configuration
################################################################

homeassistant:
  name: Torn Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/New_York
  unit_system: imperial
  customize: !include customize.yaml

#  customize: !include_dir_named customize
  packages: !include_dir_named packages
  whitelist_external_dirs:
     - /config
     - /config/snapshot
#  binary_sensor: !include binary_sensor.yaml
cloud:
  alexa:
    filter:
      include_domains:
        - switch
        - light
        - group
frontend:
  javascript_version: latest
  themes: !include themes.yaml
history:
logbook:
sun:
#updater:
circadian_lighting:
discovery:
system_health:
weather:
    - platform: darksky
      api_key: !secret darksky_api_key
      mode: daily
shopping_list:
custom_updater:
#  mode: storage
  show_installable: false
  hide_sensor: true
  track:
    - components
    - cards
    - python_scripts
  card_urls:
      - https://raw.githubusercontent.com/thomasloven/lovelace-card-modder/master/card-modder.json
      - https://raw.githubusercontent.com/custom-cards/upcoming-media-card/master/upcoming-media-card.json
      - https://raw.githubusercontent.com/thomasloven/lovelace-auto-entities/master/auto-entities.json
      - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/dark-sky-weather-card.json
      - https://raw.githubusercontent.com/thomasloven/lovelace-card-tools/master/card-tools.json
      - https://raw.githubusercontent.com/atomic7777/atomic_calendar/master/tracker.json
      - https://raw.githubusercontent.com/MizterB/lovelace-secondaryinfo-entity-row/master/custom_cards.json
      - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
      - https://raw.githubusercontent.com/cbulock/lovelace-battery-entity/master/battery-entity.js
  #    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/alexa_media/media_player.py
#lovelace:
#  mode: yaml
################################################
## Components (Non-Includes)
################################################
config:
ring:
  username: !secret ring_USERNAME
  password: !secret ring_PASSWORD
#sense:
#    email: !secret sense_USERNAME
#    password: !secret sense_PASSWORD
person:
  - name: Charlie
    id: fb905228d4fb4c2fbe6e7fd6fdaafd37
    device_trackers:
      - device_tracker.tornado

  - name: Liz
    id: 5abfb49ac65f45b8a64370c8f5241faa
    device_trackers:
      - device_tracker.lynx

  - name: Nina
    id: 5875f83e3fbc4f5c9d74c888c062e1eb
    device_trackers:
      - device_tracker.nina

  - name: Jasmin
    id: 03666e0af8bc423baf80911fefe6aeeb
    device_trackers:
      - device_tracker.monkey

  - name: Ferina
    id: f3c70a918f524eadb454f988e156088c
    device_trackers:
      - device_tracker.ferina
ifttt:
  key: !secret iftt_key
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - 'hvac_state'
      - 'humidity'
      - 'operation_mode'
      - 'temperature'
      - 'target'
      - 'co_status'
      - 'smoke_status'
      - 'battery_health'
      - 'color_status'
stream:
climate:
  platform: nest

#http:
#  api_password: !secret http_api_password
#  ssl_certificate: !secret http_ssl_certificate
#  ssl_key: !secret http_ssl_key

wink:
emulated_hue:
  host_ip: !secret hue_host
  type: alexa
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - input_boolean
    - switch
    - light

google:
  client_id: !secret client_id
  client_secret: !secret client_secret

remote:
  - platform: !secret remote_platform
    name: !secret remote_name
    host: !secret remote_host

wemo:
  static:
    - !secret wemo_one
    - !secret wemo_two
    - !secret wemo_three
    - !secret wemo_four
    - !secret wemo_five

ffmpeg:
#  ffmpeg_bin: !secret ffmpeg_bin
camera:
  - platform: ffmpeg
    name: cat camera
    input: !secret cam_input
  - platform: ffmpeg
    name: pool camera
    input: !secret cam_indoor_input
  - platform: ring
  - platform: generic
    name: Cat Stream
    still_image_url: http://192.168.1.121/jpg/image.jpg
    stream_source: rtsp://192.168.1.121:554
#camera:

media_player:
  - platform: xboxone
    device: !secret xbox_living
    authentication: false
    name: Living Room Xbox One
  - platform: xboxone
    device: !secret xbox_game
    authentication: false
    name: Game Room Xbox One

alexa_media:
  accounts:
    email: !secret amazon_email
    password: !secret amazon_password
    url: amazon.com

recorder:
  purge_interval: 1
  #db_url: !secret db_url
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun   # Don't record sun data
zwave:
  device_config: !include zwave_device_config.yaml




panel_custom: !include panel_custom.yaml

################################################
## Component Includes (Single File)
################################################

# emulated_hue: !include emulated_hue.yaml
#icloud: !include icloud.yaml
logger: !include logger.yaml
#zwave: !include zwave.yaml
#group: !include groups.yaml

################################################
## Component Includes (Named)
################################################

# alexa:
#   intents: !include_dir_named alexa

################################################
## Component Includes (Merge List)
################################################
automation: !include automation.yaml
#automation old: !include_dir_merge_list automation
#automation: !include_dir_merge_list automation
#binary_sensor: !include binary_sensor.yaml
#binary_sensor: !include_dir_merge_list binary_sensor
#camera: !include_dir_merge_list camera
#cover: !include_dir_merge_list cover
device_tracker: !include_dir_merge_list device
#light: !include_dir_merge_list light
#media_player: !include_dir_merge_list media_player
#notify: !include_dir_merge_list notify
#ios: !include_dir_merge_list ios
#scene: !include_dir_merge_list scene
#sensor: !include_dir_merge_list sensor
#switch: !include_dir_merge_list switches
#zone: !include_dir_merge_list zone

################################################
## Component Includes (Merge Named)
################################################

#group: !include_dir_merge_named group
#input_boolean: !include_dir_merge_named input_boolean
#input_select: !include_dir_merge_named input_select
#input_slider: !include_dir_merge_named input_slider
#script: !include_dir_merge_named script
#shell_command: !include_dir_merge_named shell_command
