################################################################
## Configuration
################################################################

homeassistant:
#  name: Torn Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
#  elevation: !secret home_elevation
#  time_zone: America/New_York
#  unit_system: imperial
#  customize: !include customize.yaml

#  customize: !include_dir_named customize
  packages: !include_dir_named packages
  whitelist_external_dirs:
     - /config
     - /config/snapshot
#  binary_sensor: !include binary_sensor.yaml
cloud:
#  alexa:
#    filter:
  #    include_entities:
    #    - input_boolean.light_75
#      include_domains:
#        - switch
#        - light
  #      - climate

#frontend:
#  javascript_version: latest
#  themes: !include themes.yaml

mobile_app:
rest_command:
  trigger_monkey:
    url: https://api.voicemonkey.io/trigger
    method: POST
    verify_ssl: true
    content_type: "application/json; charset=utf-8"
    payload: '{"access_token":"8bd78641c716e053ee1d740ee638fb97" ,"secret_token":"Yee1af7603757cafaeb17c4ef8b8969d9","monkey":"{{test-game-room}}","announcement":"{{announcement}}"}'

# Example configuration.yaml entry with include
history:
  include:
    domains:
      - sensor
      - switch
      - light
      - media_player
      - motion
      - binary_sensor
logbook:
sun:
#updater:
#upnp:
#  local_ip: 192.168.1.1
circadian_lighting:
discovery:
#octoprint:
#  host: !secret OCTOPRINT_HOST
#  api_key: !secret OCTOPRINT_API_KEY

system_health:
weather:
#    - platform: darksky
 #     api_key: !secret darksky_api_key
  #    mode: daily
#shopping_list:
hacs:
  token: !secret my_github_access_token

################################################
## Components (Non-Includes)
################################################
config:
ring:
  username: !secret ring_USERNAME
  password: !secret ring_PASSWORD
#sense:
#    email: !secret sense_USERNAME
#    password: !secret sense_PASSWORD

#ifttt:
 # key: !secret iftt_key
#nest:
 # client_id: !secret nest_client_id
 # client_secret: !secret nest_client_secret
 # project_id: !secret nest_PROJECT_ID
#  sensors:
#    monitored_conditions:
#      - 'hvac_state'
#      - 'humidity'
#      - 'operation_mode'
#      - 'temperature'
#      - 'target'
#      - 'co_status'
#      - 'smoke_status'
#      - 'battery_health'
#      - 'color_status'
stream:
#climate:
#  platform: nest

#http:
#  api_password: !secret http_api_password
#  ssl_certificate: !secret http_ssl_certificate
#  ssl_key: !secret http_ssl_key

#wink:
#emulated_hue:
#  host_ip: !secret hue_host
#  listen_port: 8300
#  advertise_ip: 10.0.0.10
#  advertise_port: 8080
#  type: alexa
#  off_maps_to_on_domains:
#    - script
#    - scene
#  expose_by_default: true
#  exposed_domains:
#    - input_boolean
#    - switch
#    - light
default_config:
#google:
#  client_id: !secret client_id
#  client_secret: !secret client_secret

remote:
  - platform: !secret remote_platform
    name: !secret remote_name
    host: !secret remote_host



 # organization: !secret influx_organization
 # token: !secret influx_token
wemo:
  discovery: false
  static:
    - !secret wemo_one
    - !secret wemo_two
    - !secret wemo_three
#    - !secret wemo_four
#    - !secret wemo_five
#    - !secret wemo_six
    - !secret wemo_seven
#    - !secret wemo_eight

#tplink:
#  discovery: false
#  static:
#    - !secret tp_one
#    - !secret tp_two
#    - !secret tp_three
#    - !secret tp_four
#    - !secret tp_five
#    - !secret tp_six
#    - !secret tp_seven
#    - !secret tp_eight
#ffmpeg:
#  ffmpeg_bin: !secret ffmpeg_bin
#camera:
#  - platform: ffmpeg
#    name: cat camera
#    input: !secret cam_input
#  - platform: ffmpeg
#    name: pool camera
#    input: !secret cam_indoor_input
#  - platform: ring
#  - platform: generic
#    name: Cat Stream
#    still_image_url: http://192.168.1.128/jpg/image.jpg
#    stream_source: rtsp://192.168.1.128:554
#  - platform: mjpeg
#    mjpeg_url: http://192.168.1.32:84/mjpg/pool
#    name: Pool Camera
#    username: !secret bi_username
#    password: !secret bi_password
#    authentication: basic
#  - platform: mjpeg
#    mjpeg_url: !secret 3d_printer_address
#    name: Printer Camera
#camera:
#breaking_changes:
media_player:

#  - platform: denon
#    host: 192.168.1.8
#    name: Torn Theater
#    show_all_sources: true
#    timeout: 3
#    zones:
#      - zone: Zone2
#        name: NAME


#  - platform: xboxone
#    device: !secret xbox_living
#    authentication: true
#    name: Living Room Xbox One
#  - platform: xboxone
#    device: !secret xbox_game
#    authentication: false
#    name: Game Room Xbox One
#samsungtv:
#  host: 192.168.1.51
#    port: 8002
#    method: websocket
#plex:
#  host: !secret plex_host
#  port: !secret plex_port
#  token: !secret plex_token
#  ssl: true
#  verify_ssl: true
#  media_player:
#    use_episode_art: true
#    show_all_controls: false
alexa_media:
  accounts:
    email: !secret amazon_email
    password: !secret amazon_password
    url: amazon.com

recorder:
  #purge_interval: 1
  #db_url: !secret db_url
  #purge_keep_days: 5
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
   # Don't record sun data
#zwave:
#  usb_path: /dev/ttyACM0
#  device_config: !include zwave_device_config.yaml

panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: !secret node_red_url
#  octoprint:
#    title: Octoprint
#    icon: mdi:printer-3d
#    url: !secret octoprint_url
# Example configuration.yaml entry for Netgear device
#device_tracker:
#  - platform: netgear
#    host: IP_ADDRESS
#    username: YOUR_USERNAME
#    password: YOUR_PASSWORD
#    new_device_defaults:
#      track_new_devices: true
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
    hosts:
      Charlie: 10.0.2.6
      Liz: 10.0.2.8
#panel_custom: !include panel_custom.yaml

################################################
## Component Includes (Single File)
################################################

# emulated_hue: !include emulated_hue.yaml
#icloud: !include icloud.yaml
logger: !include logger.yaml
#zwave: !include zwave.yaml
group: !include groups.yaml

################################################
## Component Includes (Named)
################################################

# alexa:
#   intents: !include_dir_named alexa
#themes: !include themes.yaml
################################################
## Component Includes (Merge List)
################################################
automation: !include automations.yaml
#automation old: !include_dir_merge_list automation
#automation: !include_dir_merge_list automation
#binary_sensor: !include binary_sensor.yaml
#binary_sensor: !include_dir_merge_list binary_sensor
#camera: !include_dir_merge_list camera
#cover: !include_dir_merge_list cover
#device_tracker: !include_dir_merge_list device
#light: !include_dir_merge_list light
#media_player: !include_dir_merge_list media_player
#notify: !include_dir_merge_list notify
#ios: !include_dir_merge_list ios
scene: !include_dir_merge_list scene
#sensor: !include_dir_merge_list sensor
#template: !include_dir_merge_list templates
#switch: !include_dir_merge_list switches
#zone: !include_dir_merge_list zone
influxdb: !include influxdb.yaml
################################################
## Component Includes (Merge Named)
################################################

#group: !include_dir_merge_named group
#input_boolean: !include_dir_merge_named input_boolean
#input_select: !include_dir_merge_named input_select
#input_slider: !include_dir_merge_named input_slider
script: !include scripts.yaml #!include_dir_merge_named script
#shell_command: !include_dir_merge_named shell_command
