resources:
  - url: /local/custom_ui/weather-card.js
    type: js

title: Home Assistant
views:
  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
  #  garage_door_tilt_sensor_alarm_level: Weather
    cards:
      - type: "custom:weather-card"
        entity_weather: weather.yweather
        entity_sun: sun.sun
      - type: entities
        title: Weather
        entities:
          - sensor.yweather_condition
          - sensor.yweather_current
          - sensor.yweather_humidity
          - sensor.yweather_pressure
          - sensor.yweather_temperature
          - sensor.yweather_temperature_max
          - sensor.yweather_temperature_min
          - sensor.yweather_visibility
          - sensor.yweather_wind_speed