- alias: "Porch Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_slider.porch_animation_speed
  action:
    - service: mqtt.publish
      data_template:
        topic: "bruh/mqttstrip/setanimationspeed"
        payload: '{{ trigger.to_state.state | int }}'
