- alias: 'Notify if any doors left open for 10 minutes'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.fortrezz_mimolite_wireless_interfacebridge_module_sensor_5_0
    state: 'closed'
    for:
      minutes: 10
  action:
    service: notify.notify
    data_template:
      message: >
          The {{ trigger.to_state.attributes.friendly_name }} was left open
