- alias: Turn on Kitchen light when there is movement
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_31_10
    to: '8'
  action:
    service: light.turn_on
    entity_id: light.ge_12724_3way_dimmer_switch_level_9_0, light.zooz_zen22_zwave_plus_dimmer_light_switch_level_5_0
- alias: Turn off Kitchen light when there is no movement
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_31_10
    to: '0'
  action:
    service: light.turn_off
    entity_id: light.ge_12724_3way_dimmer_switch_level_9_0, light.zooz_zen22_zwave_plus_dimmer_light_switch_level_5_0
