- alias: Minimote Button 1 Pressed
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_57
      scene_id: 1
  condition:
    - condition: state
      entity_id: switch.deck_motion
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.deck_motion
