- alias: 24 minimote_button_1_pressed
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        object_id: aeotec_dsa03202_minimote_24
        scene_id: 1
  action:
    - service: light.toggle
      data:
        entity_id: light.aeotec_dsc27103_micro_dimmer_2nd_edition_level_8_0
      #  brightness: 128
- alias: 24 full minimote_button_1_held
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        object_id: aeotec_dsa03202_minimote_24
        scene_id: 2
  action:
    - service: light.turn_on
      data:
        entity_id: light.aeotec_dsc27103_micro_dimmer_2nd_edition_level_8_0
        brightness: 128
- alias: 24  Minimote Button 2 pressed
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_24
      scene_id: 3
  action:
    - service: light.turn_on
      data:
        entity_id: light.aeotec_dsc27103_micro_dimmer_2nd_edition_level_8_0
        brightness: 254
- alias: 24 2 Minimote Button 2 held
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_24
      scene_id: 4
  action:
    - service: switch.toggle
      data:
        entity_id: switch.master_bedroom_light
    #    brightness: 128
- alias: 24 2 Minimote Button 3 pressed
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_24
      scene_id: 5
  action:
    service: light.toggle
    entity_id: switch.master_bedroom_light
- alias: 24 3 Minimote Button 3 Held
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_24
      scene_id: 6
  action:
    - service: light.turn_on
      data:
        entity_id: light.ge_12724_3way_dimmer_switch_level_16_0
        brightness: 128
- alias: 24 3 Minimote Button 3 held
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_24
      scene_id: 7
  action:
    service: switch.toggle
    entity_id: light.aeotec_dsc27103_micro_dimmer_2nd_edition_level_8_0
    data:
      brightness: 100
- alias: 24 4 Minimote Button 4 Pressed
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: aeotec_dsa03202_minimote_24
      scene_id: 8
  action:
    service: switch.toggle
    entity_id: switch.tv_room_lights
    data:
      brightness: 100
 #   brightness: 50
