- alias: tV Lights on
  trigger:
    - platform: state
      entity_id: sensor.vizio_tv
      to: 'Online'
  action:
    - service: light.turn_on
      entity_id: light.ge_12724_3way_dimmer_switch_level_16_0
- alias: tv lights off
  trigger:
    platform: state
    entity_id: sensor.vizio_tv
    to: 'offline'
  action:
    service: light.turn_off
    entity_id: light.ge_12724_3way_dimmer_switch_level_16_0
