- alias: Turn theater lights to 80 on motion if no activity
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_32_10
    from: '0'
    to: '8'
  condition:
    condition: state
    entity_id: sensor.tv_room
    state: 'PowerOff'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_theater_lights
