# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/more_page.html

# more_page:
#   addons:
#     - name: Hello more page
#       icon: fas:chart-area
#       path: 'dwains-theme/addons/more_page/hello-more-page/page.yaml'
#       data:
#         some_data: 'This is some data parsed.'
#         some_other_data: 'and some other data.'