- platform: template
  sensors:
     vizio_tv:
        friendly_name: 'Vizio TV'
        value_template: "{{ 'Online' if is_state('device_tracker.vizio_tv', 'home') else 'Offline' }}"

     broadlink:
        friendly_name: 'Broadlink'
        value_template: "{{ 'Online' if is_state('device_tracker.broadlink', 'home') else 'Offline' }}"

     harmony_hub:
        friendly_name: 'Harmony Hub'
        value_template: "{{ 'Online' if is_state('device_tracker.harmonyhub', 'home') else 'Offline' }}"

     tv_room:
        friendly_name: 'Tv Room'
        value_template: "{{ states.remote.torn_hub.attributes.current_activity }}"


  #   Harmony_hub:
  #      friendly_name: 'Harmony Hub'
  #      value_template: "{{ 'Online' if is_state('device_tracker.harmonyhub', 'home') else 'Offline' }}"
