- platform: template
  sensors:
    internet_speed_in:
      friendly_name: 'Internet Speed'
      value_template: '{{ ((states.input_slider.internet_traffic_delta_in.state | float ) / 1000000 ) | round(2) }}'
      unit_of_measurement: 'Mbps'
    internet_speed_out:
      friendly_name: 'Internet Speed'
      value_template: '{{ ((states.input_slider.internet_traffic_delta_out.state | float ) / 1000000 ) | round(2) }}'
      unit_of_measurement: 'Mbps'

- platform: statistics
  name: 'WAN Traffic IN'
  entity_id: sensor.internet_speed_in

- platform: statistics
  name: 'WAN Traffic OUT'
  entity_id: sensor.internet_speed_out   
