#  Monitor internet connection speed.

- platform: template
  sensors:
    motion_status:
      value_template: '{% if states.sensor.aeotec_zw100_multisensor_6_burglar_32_10 %}
        {% if states.sensor.aeotec_zw100_multisensor_6_burglar_32_10.state == "8" %}
          motion
        {% else %}
          off
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      friendly_name: 'motion Status'
