## this is based on a split configuration setup.
## place this code into a seporate yaml file and place it in a folder labled sensor in your root homeassistant location
## add this entry to your configuration file. sensor: !include_dir_merge_list sensors
## alter code below to fit your needs

- platform: template
  sensors:
    garage_door_status:
      value_template: '{% if states.binary_sensor.fortrezz_mimolite_wireless_interfacebridge_module_sensor_2_0 %}
        {% if states.binary_sensor.fortrezz_mimolite_wireless_interfacebridge_module_sensor_2_0.state == "on" %}
          Open
        {% else %}
          Closed
        {% endif %}
        {% else %}
        n/a
        {% endif %}'
      friendly_name: 'Garage Door Status'
