
#    - ozone
#      - minutely_summary
#    - hourly_summary
#    - daily_summary
#    - temperature_max
#    - temperature_min
#    - apparent_temperature_max
#    - apparent_temperature_min
#    - precip_intensity_max

#- platform: sonarr
#  api_key: !secret sonarr_api_key
#  host: !secret sonarr_url
#  port: !secret sonarr_port
#  monitored_conditions:
#    - diskspace
#    - upcoming
#  days: 1
- platform: yweather
#  name: Weather
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature

- platform: ring
- platform: google_wifi



- platform: yr
- platform: speedtest
  monitored_conditions:
  - ping
  - download
  - upload

- platform: template
  sensors:
     vizio_tv:

     harmony_hub:
        friendly_name: 'Harmony Hub'
        value_template: "{{ 'Online' if is_state('device_tracker.harmonyhub', 'home') else 'Offline' }}"

     tv_room:
        friendly_name: 'Tv Room'
        value_template: "{{ states.remote.torn_hub.attributes.current_activity }}"
