####SENSOR BASED####
#- !include automation/motion_downstairs.yaml
- alias: Turn on attic light when door opened
  trigger:
    platform: state
    entity_id: binary_sensor.everspring_hsp02_motion_detector_sensor_15_0
    to: 'open'
  action:
    service: homeassistant.turn_on
    entity_id: light.unknown_id015d_unknown_type0112_id241c_level_3_0
- alias: Turn off attic light when door is closed
  trigger:
    platform: state
    entity_id: binary_sensor.everspring_hsp02_motion_detector_sensor_15_0
    to: 'closed'
  action:
    service: homeassistant.turn_off
    entity_id: light.unknown_id015d_unknown_type0112_id241c_level_3_0
