  - alias: tts garage door opened #creates the action button
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.garage_door_status
      from: 'Closed'
      to: 'Open'
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "The Garage Door Has Been Opened"

  - alias: tts garage door closed #creates the action button
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.garage_door_status
      from: 'Open'
      to: 'Closed'
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "The Garage Door Has Been closed"

  - alias: tts front eave lights #creates the action button
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.front_eave_led_lights
      from: 'off'
      to: 'on'
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "Front   eave   lights   have   turned   on"
          
  - alias: tts motion front door #creates the notification
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.front_door_motion
  #    from: 'no motion'
      to: 'motion'  #change this to actual trigger
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "Motion at the front door"


  - alias: tts Trash Reminder
    trigger:
      - platform: time
        at: '20:00:00'
      - platform: time
        at: '21:00:00'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.torn8o_trash_day
        state: 'yes'
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "Tomorrow is the Trash Pickup day. Put the Trash bin outside, please!"

  - alias: tts recycle Reminder
    trigger:
      - platform: time
        at: '20:00:00'
      - platform: time
        at: '21:00:00'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.torn8o_recycle_day
        state: 'yes'
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "Tomorrow is the Recycle Pickup day. Put the Recycle bin outside, please!"
#    Tomorrow is the Recycle Pickup day. Put the Recycle bin outside, please!
