#   alias: Trash - Enable trash Lighting
#   trigger:
#      - platform: state
#        entity_id: calendar.trash_and_recycle
#        to: 'on'
#        for:
#          hours: 9
#          minutes: 0
#          seconds: 0
 
#   condition:
#     condition: or
#     conditions:
#       - condition: state
#         entity_id: sensor.trash_and_recycle
#         state: 'Put Trash Out'
 
#   action:
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.trash
#         option: 'Trash'

#  alias: light trash Reminder
#  initial_state: True
#  trigger:
#     - platform: time_pattern
#       at: '20:00:00'
#     - platform: time_pattern
#       at: '21:00:00'
#   condition:
#     condition: or
#     conditions:
#     - condition: state
#       entity_id: sensor.trash_and_recycle
#       state: 'Put Trash Out'
#   action:
#     - service: light.turn_on
#       entity_id: light.niche_leds
#       data:
#         transition: 900
#         brightness_pct: 100
#         color_name: purple
#         effect: Rainbow

#  alias: light recycle Reminder
#  initial_state: True
#  trigger:
#     - platform: time_pattern
#       at: '20:00:00'
#     - platform: time_pattern
#       at: '21:00:00'
#   condition:
#     condition: or
#     conditions:
#     - condition: state
#       entity_id: sensor.trash_and_recycle
#       state: 'Put Recycle Out'
#   action:
#     - service: light.turn_on
#       entity_id: light.niche_leds
#       data:
#         transition: 900
#         brightness_pct: 100
#         color_name: purple
#         effect: rainbow
  - alias: tts garage door opened #creates the action button
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.garage_door_status
      from: 'Closed'
      to: 'Open'
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "The Garage Door Has Been Opened"

  - alias: tts garage door closed #creates the action button
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.garage_door_status
      from: 'Open'
      to: 'Closed'
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "The Garage Door Has Been closed"

  - alias: tts front eave lights #creates the action button
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.front_eave_led_lights
      from: 'off'
      to: 'on'
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "Front   eave   lights   have   turned   on"

  - alias: tts motion front door #creates the notification
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.front_door_motion
  #    from: 'no motion'
      to: 'motion'  #change this to actual trigger
    action:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          message: "Motion at the front door"
