# car sensor is connected and the garage door is closed


- alias: CarPresence_ON
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.carpresence
    to: 'on'
  condition:
  - condition: state
    entity_id: 'sensor.garage_door_status'
    state: 'Closed'
  action:
  - service: switch.turn_on
    entity_id: 'switch.garage_door_opener_switch'

# car sensor is disconnected for one minute and the garage door is open
- alias: CarPresence_OFF
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.carpresence
    to: 'off'
    for:
      minutes: 1
  condition:
  - condition: state
    entity_id: 'sensor.garage_door_status'
    state: 'Open'
  action:
  - service: switch.turn_on
    entity_id: 'switch.garage_door_opener_switch'
