- alias: "Turn ON Day Star"
  trigger:
    - platform: state
      entity_id: input_boolean.day_star
      to: 'on'
  action:
    - service: cover.open_cover
      entity_id: cover.curtains

- alias: "Turn OFF Day Star"
  trigger:
    - platform: state
      entity_id: input_boolean.day_star
      to: 'off'
  action:
    - service: cover.close_cover
      entity_id: cover.curtains
