- alias: open curtains sunrise
  hide_entity: false
  trigger:
    platform: sun
    event: sunrise
  action:
    service: switch.turn_on
    entity_id: switch.receiver5
#- alias: curtain open
#  trigger:
#    platform: time
#    seconds: '/15'
#  condition:
#    - condition: state
#      entity_id: switch.receiver5
#      state: "on"
#  action:
#    - service: switch.turn_on
#      data:
#        entity_id: switch.receiver5
- alias: close curtains sunset
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.receiver4
