######################################################################
##  Dark House Little extra light - DARK and Cloudy or just rainy.
######################################################################

- alias: 'Dark outside light'
  initial_state: True
  trigger:
  #  - platform: numeric_state
  #    entity_id: sun.sun
  #    value_template: '{{ state.attributes.elevation }}'
  #    below: 20.0
    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 80
  #  - platform: numeric_state
  #    entity_id: sensor.dark_sky_precip_intensity
  #    above: 1

  condition:
  #  condition: and
  #  conditions:
  #    - condition: or
  #      conditions:
  #        - condition: and
  #          conditions:
  #            - condition: numeric_state
  #              entity_id: sun.sun
  #              value_template: '{{ state.attributes.elevation }}'
  #              below: 20.0
              - condition: numeric_state
                entity_id: sensor.dark_sky_cloud_coverage
                above: 80
  #        - condition: numeric_state
  #          entity_id: sensor.dark_sky_precip_intensity
  #          above: 1
  #    - condition: state
  #      entity_id: sun.sun
  #      state: 'above_horizon'

  action:
    - service: switch.turn_on
      entity_id:
#        - switch.front_lights_switch_28_0
        - light.front_entry_level


######################################################################
