- alias: View lights
  initial_state: True
#  automation 2:
  trigger:
    platform: sun
    event: sunrise
  action:
    service: group.set_visibility
    entity_id: group.lights1
    data:
      visible: True
