- alias: Turn Holiday Led On At Sunset
  hide_entity: false
  trigger:
    platform: sun
    event: sunset
    offset: '00:01:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.led_lights

- alias: 'Holiday Led Stuff off'
  trigger:
    platform: sun
    event: sunrise
    offset: '-07:34:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.led_lights
