homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'alexa'

script:
  alexa_set_volume:
  sequence:
    - service: media_player.volume_set
      data_template: 
        entity_id: '{{ states.sensor.last_alexa.state }}' 
        volume_level: >
          {% if is_state("sensor.last_alexa", "media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom") %}
            0.5
          {% else %}
            0.3
          {% endif %} 
sensor:
  - platform: template
    sensors:
      last_alexa:
        entity_id:
          - media_player.game_room	
          - media_player.garage	
          - media_player.kitchen	
          - media_player.living_room	
          - media_player.master_bedroom
      value_template: >
        {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}