
homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'Center sensor'
light:
  - platform: mqtt
    schema: json
    name: "Center_LED"
    state_topic: "torn/center"
    command_topic: "torn/center/set"
    brightness: true
#    flash: true
    rgb: true
    optimistic: false
    qos: 0



sensor:

  - platform: mqtt
    state_topic: "torn/center"
    name: "Center Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "torn/center"
    name: "Center LDR"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "torn/center"
    name: "Center PIR"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/center"
    name: "Center Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "front/motion"
    name: "front door motion"

  - platform: mqtt
    state_topic: "pool/motion"
    name: "pool door motion"

  - platform: mqtt
    state_topic: "torn/center"
    name: "Center Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: template
    sensors:
      center_motion_status:
        value_template: '{% if states.sensor.Center_Pir %}
          {% if states.sensor.Center_Pir.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

automation:


#  - service: notify.slacknotify
#    data:
#      message: "Front Door camera snapshot"
#      data:
#        file:
#          path: "config/snapshot/cam.jpg"

#action:
#  service: notify.NOTIFIER_NAME
#  data:
#    title: Send file
#    message: This is a file
#    data:
#      file: /path/to/my/file
#      service: notify.slacknotify
#      message: "front door"
  #    target: ["danny_pixel", "tosh_phone"]
#      title: Shokabow Zoo
#  - service: notify.slacknotify
#    data:
#      message: "Front Door camera snapshot"
#      data:
#        file:
#          path: "config/snapshot/cam.jpg"
#  - delay: "00:00:30"
#  - service: switch.turn_on
#    entity_id: switch.lr_alarm





  - alias: Turn Kitchen light on
    initial_state: True
    trigger:
      platform: state
      entity_id: group.kitchen_motion
      to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.kitchen_leds
#      - delay:
#          minutes: 1
#      - service: switch.turn_off
#        entity_id: group.kitchen_lights

  - alias: Turn off kitchen light
    initial_state: True
    trigger:
      platform: state
      entity_id: group.kitchen_motion
      to: 'off'
      for:
        seconds: 45
    action:
      service: light.turn_off
      entity_id: light.kitchen_leds

  - alias: Turn light led on
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.center_pir
      to: 'motion detected'
    action:
      - service: light.turn_on
        entity_id: light.Center_led
        data:
          color_name: 'purple'

  - alias: Turn light led off center
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.center_pir
      to: 'standby'
      for:
        seconds: 2
    action:
      - service: light.turn_off
        entity_id: light.Center_led






group:
  Center_sensor:
    name: Center Sensor
#    view: yes
    entities:
      - sensor.Center_Temperature
      - sensor.Center_Humidity
      - sensor.Center_Ldr
      - sensor.Center_Pir
      - light.Center_LED
      - automation.turn_off_kitchen_light
