
################################################
## Customize
################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'circadian_lighting'

    ################################################
    ## switch
    ################################################
light:
  - platform: group
    name: Theater Room Lights
    entities:
#      - light.spot_light_level
      - light.tv_room_light_level
  - platform: group
    name: Hallway Lights
    entities:
      - light.hallway_1
      - light.hallway_2
      
switch:
  - platform: circadian_lighting
    lights_ct:
      - light.hallway_lights
    min_brightness: 15
    max_brightness: 70
    name: CL hallway Lights
  - platform: circadian_lighting
    lights_ct:
      - light.hair_area_level
    min_brightness: 35
    max_brightness: 70
    name: Hair Lights
  - platform: circadian_lighting
    lights_ct:
      - light.theater_room_lights
    min_brightness: 30
    max_brightness: 100
    name: Theater Room Circadian
  - platform: circadian_lighting
    lights_ct:
      - light.kitchen_leds
    min_brightness: 30
    max_brightness: 100
    name: Kitchen Lights
#  - platform: circadian_lighting
#    lights_brightness:
#      - light.accent_interior_lights
#    name: accent
