# Description:
#   Broadlink RM Input Select work around for fan speed selection
#
# Written for:
#   @torn8o01_twitter
#
# Components:
#   automation
#   input_select
#   switch
#
# License:
#   MIT
#
# Author:
#   Dale Higgs <@dale3h>
#
# PLEASE NOTE: THIS CONFIGURATION IS UNTESTED AND MAY CONTAIN ERRORS

automation:
  - alias: fan_speed_selected
    trigger:
      - platform: state
        entity_id: input_select.fan_speed
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'Select an option...' }}"
    action:
            # Turn on the wall switch to make sure it receives the command
      - service: switch.turn_on
        data:
          entity_id: switch.tv_room_fan
      - delay: '00:00:05'
      # Turn the corresponding switch on to send the fan speed command
      - service: switch.turn_on
        data_template:
          entity_id: "switch.fan_speed_{{ trigger.to_state.state|lower|replace(' ', '_') }}"
      # Reset the Input Select to "Select an option..."
      - service: input_select.select_option
        data_template:
          entity_id: "{{ trigger.to_state.entity_id }}"
          option: Select an option...

input_select:
  fan_speed:
    initial: Select an option...
    options:
      - Select an option...
      - Off
      - Low
      - Medium
      - High

switch:
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    name: !secret broadlink_name
    switches:
     receiver:
       friendly_name: Fan Speed Off
       command_on: 'sgc0AA8OGw4bDhsaDhsPDhsOGw4cDhsbDw4bDhsaDw4bDhsOGw4bDhsOGxoPDhsaDw4bGw4AAawAAAAA'
     receiver1:
       friendly_name: Fan Speed Low
       command_on: 'sgY0AA8OGw4aDhsaDhoODhsOGg4bDhsaDg4bDhsaDg4bDhsOGxoPDhsOGg4bDhsbDg4aGw4AAawAAAAA'
     receiver2:
       friendly_name: Fan Speed Medium
       command_on: sgo0AA8OGw4bDhsaDxoPDhsOGw4bDhsaDg8bDhsbDw4bDhsOHA4bGw4OGw4bDhsaDg4bGw4AAa0AAAAA'
     receiver3:
       friendly_name: Fan Speed High
       command_on: 'sgk0AA8OGw4bDhsaDhsPDhsOGg4bDhsaDw4bDhsaDg4bDhsOGxoOGg8OGw4bDhsaDw4aGg4AAawAAAAA'
     receiver4:
       friendly_name: Living room curtain close
       command_on: 'JgA0ACwNKgwPKCsNDygOKSsKESgOKQ8pDikOAAR4Kw0qDg4oKwwPKA4pKw0OKg4pDikOKQ4ADQUAAAAA'
    #   command_off: 'JgBoACsMKw0OKSoNDygPKA8oDygrDg4oDygPAAR4Kg4pDg4oKw0OKQ8oDygPKCsMDygPKQ8AC1wrDikNDygrDQ4oDykPKA8oKg4OKA8oEAAEdysMKw0OKQ8oDygPKBAnDygQKA8oDygPAA0F'
     receiver5:
       friendly_name: Living room curtain open
       command_on: 'JgBoACoOKQ0PKCwMDikOKQ8oKg4OKA8pDygOAAR4Kw0qDQ4pKg4MKg4pDygrDQ4pDSoPKA8AC10pDykODigrDQ4qDigPKQ4oDygPKQ4pDwAEdyoOKgsQKQ8oDygPKA8pDioOKQ4oDykOAA0F'
       #command_off: 'JgBoACsMKw0OKSoNDygPKA8oDygrDg4oDygPAAR4Kg4pDg4oKw0OKQ8oDygPKCsMDygPKQ8AC1wrDikNDygrDQ4oDykPKA8oKg4OKA8oEAAEdysMKw0OKQ8oDygPKBAnDygQKA8oDygPAA0F'
     receiver6:
       friendly_name: Living room curtain stop
       command_on: 'JgBoACsMKw0OKSoNDygPKA8oDygrDg4oDygPAAR4Kg4pDg4oKw0OKQ8oDygPKCsMDygPKQ8AC1wrDikNDygrDQ4oDykPKA8oKg4OKA8oEAAEdysMKw0OKQ8oDygPKBAnDygQKA8oDygPAA0F'
  #     command_off: 'JgBoACoOKQ0PKCwMDikOKQ8oKg4OKA8pDygOAAR4Kw0qDQ4pKg4MKg4pDygrDQ4pDSoPKA8AC10pDykODigrDQ4qDigPKQ4oDygPKQ4pDwAEdyoOKgsQKQ8oDygPKA8pDioOK'
    
     #receiver7:
    #   friendly_name: master bedroom wall lights
    #   command_on: 'CEA8AAAACFBCBCDFECBEFEBAEBADABCCACFECBEE2FEFEEECBEECAAECCCCBEEBE2BEBEEECA4AAAACCACBEEFE4EBEEEBADABACACCEEBAEFEFEEEEEAAECCCCBAECCBEBEFEBAE0AAECCCAECBBEBE1EBAECBADABACACCEECEEFEFEEEEEAAECCCC0EBEBEBECEEC4AAACCACBEEBECBEFEEEDABDACCECBAEFEBEAECBAECAAECCCCBEEBFEFEFEEEA0AAECCCAEFEFEFEEECBADABCC8CEEAEBEFEEEAEAAECCACCEEBEFEBEEE0AAECCCBEEFEFEFEEEBADAF3AAAAAA'
    #   command_off: 'B2A6A81C1FFEE'
  #   receiver8:
  #     friendly_name: master bedroom2 wall lights
  #command_on:'sgGEAw0AAR8JGQgZCRgJGAkYCRgJGAkZCRgJQxAiECIQIhBkD2UPZQ9kEGQQZBBkD2UPIw8jDyMPIw8jDAABIAkYCRgJGAkYCRgJGQgZCRgJGAlDDyMQIhAiEGQPZBBkEGQPZBBkEGQPZBAjDyIQIhAjDyINAAEgCBkJGAkYCRgJGAkYChcJGQkYCUMPIxAiECIQZA9kEGQQZA9kEGQQZA9kECIQIhAjDyIQIg0AAR8KGAgZCRgJGAkYCRgJGAkZCBkJQxAiECIQIhBkD2QQZBBjEGQQZA9lEGMQIhAiECIQIw8iDQABHwkYChgIGQkYCRgJGAkYCRgJGApDECIPIw8jEGQPZBBkD2QQZBBkD2UPZBAiECIQIhAiECINAAEfChgIGQkYCRgJGAkYCRgJGAoYCUMPIw8jDyMQZA9kEGQPZQ9lD2UPZBBkECIQIg8jECIQIgwAASAJGAkYCRkIGQkYCRgJGAkYCRgJRA
  #     command_off: 'ozbrP2Aqgymn6a81zhLcYy1sFvPqvFeqQSzesw=='
     deck_led:
       friendly_name: deck led lights
       command_on: 'sgDQAA8qKxAPKioQKxAPKg8rDysPKg8rDyorECoQKhAPKw8qDysPKw8rDyoPKw8qDysqEA8AAb4PKyoQDysqECsPDysPKw8qDysPKw8qKxAqECoQDysPKhAqDysPKw8qDysPKw8qKhEPAAG+DyorEA8qKxAqEA8rDyoPKw8qECoPKyoQKhArEA8qECoPKw8rDyoPKw8rDyoPKyoQDwABvw8qKxAPKioQKxAPKg8rDysPKg8rDysqECoQKxAPKg8rDysPKg8rDyoQKg8rDysqEA8ABdwAAAAAAAAAAA=='
    #   command_off:
     #Mode_plus:
      # friendly_name: mode plus
       #command_on: 'sgAEARAqKw8PKyoQKhAPKhAqDysPKhAqDyorDysPKw8QKhAqDyoQKg8qECoQKioQDyorDxAAAb0QKioQDyorECoQDyoQKhAqDyoPKw8qKw8rECoPECoQKg8qECoPKw8qECorDw8qKxAPAAG9ECorDw8rKhArDw8qECoPKw8qECoPKisPKxArDw8qECoPKhAqECoPKhAqKw8QKioQDwABvg8qKw8QKisPKw8PKw8qECoQKRAqDyorECsPKw8QKg8qECoQKg8qECoPKisPECorDw8AAb4PKisQDyorDysPECoQKg8qECoPKhAqKw8rDysPECoPKw8qECoQKRAqECoqEA8qKxAPAAXcAAAAAA=='
    #   command_off: