homeassistant:
  customize:
    switch.garage_door_opener_switch_2_0:
      friendly_name: Double Car Garage



sensor:
  - platform: template
    sensors:
      garage_door_status:
        value_template: >-
          {% if states.binary_sensor.garage_door_opener_sensor.state == 'off' %}
            Closed
          {% elif states.binary_sensor.garage_door_opener_sensor.state == 'on' %}
            Open
          {% else %}
            Unknown
          {% endif %}
        friendly_name: Garage Door Status
        icon_template: >-
          {% set door_status = states.binary_sensor.garage_door_opener_sensor.state |d('unknown') %}
          {% if door_status == 'unknown' %}
            mdi:alert-circle
          {% else %}
            {% if door_status == 'on' %}
              mdi:garage-open
            {% else %}
              mdi:garage
            {% endif %}
          {% endif %}


automation:
  - alias: Reset Relays
    initial_state: 'on'
  #  hide_entity: true
    trigger:
      - platform: state
        entity_id:
          - switch.garage_door_opener_switch
        to: "on"
        for:
          seconds: 5
    action:
      - service_template: switch.turn_off
        data_template:
          entity_id: '{{ trigger.entity_id }}'

################################################################################
# Notifies when either of the garage door is opened or closed
# When the garage is opened, it sends an actionable ios notification with an
# option to close the garage door. This iso actionable notification only occurs
# when garage door is open and not when it is closed.
###############################################################################
#  - alias: Notify door
#    trigger:
#      platform: state
#      entity_id:
#        - sensor.garage_door_status
#      to: 'open'
#      for:
#        minutes: 1
#    action:
#      service: notify.ios_torn8o #change to your ios device name or group
#      data:
#        title: "Garage door Notification"
#        message: "Press for options"
#        data:
#          push:
#            badge: 0
#            sound: US-EN-Morgan-Freeman-Vacate-The-Premises.wav
#            category: "GARAGE_CLOSE" # Needs to match the top level identifier you used in the ios configuration
#          action_data: # Anything passed in action_data will get echoed back to Home Assistant.
#            entity_id: camera.cam
#            my_custom_data: foo_bar


  #- alias: Notify Door
  #  initial_state: true
  #  hide_entity: true
  #  trigger:
  #    platform: state
  #    entity_id:
  #      - sensor.garage_door_status
  #  condition:
  #    - condition: template
  #      value_template: "{% if trigger.from_state %} True {% else %} False {% endif %}"
  #  action:
  #    - service: notify.ios_torn8o
  #      data_template:
  #        value1: >
  #            {% if trigger.to_state.state | lower == "on" %}
  #                {{ trigger.to_state.attributes.friendly_name }} is now OPENED!
  #            {% elif trigger.to_state.state | lower == "off" %}
  #                {{ trigger.to_state.attributes.friendly_name }} is now CLOSED!
  #            {% endif %}
  #        value2: ""
  #    - service_template: >
  #        {% if trigger.to_state.state | lower == "on" %}
  #          switch.turn_on
  #        {% else %}
  #          switch.turn_off
  #        {% endif%}
  #      data:
  #        entity_id: switch.fan_speed_high
  #    - service: notify.ios_torn8o
  #      data_template:
  #        value1: >
  #          {% if trigger.to_state.state | lower == "on" %}
  #            Attention! Your {{ trigger.to_state.attributes.friendly_name }} is now OPENED!
  #          {% elif trigger.to_state.state | lower == "off" %}
  #            Attention! Your {{ trigger.to_state.attributes.friendly_name }} is now CLOSED!
  #          {% endif %}
  #    - condition: and
  #      conditions:
  #        - condition: template
  #          value_template: >
  #            {% if trigger.to_state.state | lower == "on" %}
  #              true
  #            {% else %}
  #              false
  #            {% endif %}
  #    - service: notify.ios_torn8o
  #      data_template:
  #        title: >
  #          {{ trigger.to_state.attributes.friendly_name }}
  #        message: >
  #          Attention: Your {{ trigger.to_state.attributes.friendly_name }} is now OPENED!
  #        data:
  #          push:
  #            badge: 0
  #            category: >
  #              {% if trigger.entity_id == "switch.garage_door_opener_switch_2_0" %}
  #                1CAR_GARAGE
  #              {% else %}
  #               2CAR_GARAGE
  #              {% endif%}
            # action_data:
              # entity_id: >
                # {% if trigger.entity_id == "binary_sensor.ecolink_garage_door_tilt_sensor_sensor_5_0" %}
                  # switch.linear_fs20z_isolated_contact_fixture_module_switch_13_0
                # {% else %}
                 # switch.linear_fs20z_isolated_contact_fixture_module_switch_14_0
                # {% endif%}
################################################################################
#  iOS Actionable Notification for Single Car Garage Door
################################################################################
#  - alias: Close Garage
#    initial_state: true
  #  hide_entity: true
#    trigger:
#      platform: event
#      event_type: ios.notification_action_fired
#      event_data:
#        actionName: GARAGE_CLOSE
#    action:
#      - service: notify.ios_torn8o
#        data:
#          message: "Closing Garage Door.."
#      - service: switch.turn_on
#        entity_id: switch.garage_door_opener_switch_2_0
      # - service: switch.turn_on
        # data_template:
          # entity_id: '{{ trigger.actionData.attributes["entity_id"] }}'
  - alias: Remind Me Later
    initial_state: True
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: REMIND_LATER
    action:
      - service: notify.ios_torn8o
        data:
          message: "Will remind you in a few minutes !"
#  - alias: garage reminder
#    initial_state: true
#    trigger:
#      - platform: time
#        minutes: '30'
#        seconds: '00'
#    condition:
#      condition: and
#      conditions:
#
#        value_template: '{{ states.input_boolean.garage_reminder.state == "on" }}'
#    action:
#      - service: notify.ios_torn8o
#        data:
#          title: "Garage Check"
#          message: "Please check garage"
#          data:
#            push:
#              category: "garage"
#            action_data:
#              entity_id: foo
#              my_custom_data: bar

input_boolean:
  garage_reminder:
    name: garage Reminder
    initial: on
    icon: mdi:tablet
