homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'Garage sensor'
light:
  - platform: mqtt
    schema: json
    name: "Garage_LED"
    state_topic: "torn/garage"
    command_topic: "torn/garage/set"
    brightness: true
  #  flash: true
    rgb: true
    optimistic: false
    qos: 0


switch:
  - platform: mqtt
    name: "swimming_light"
    state_topic: "stat/swimming_light/POWER"
    command_topic: "cmnd/swimming_light/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
    

sensor:
  - platform: mqtt
    name: "front door motion"
    state_topic: "front/motion"

  - platform: mqtt
    name: "pool motion"
    state_topic: "pool/motion"

  - platform: mqtt
    name: "pool motion"
    state_topic: "camera/pool/motion"



  #- platform: template
  #  sensors:
  #    garage_motion_status:
  #      value_template: '{% if states.sensor.Garage_Pir %}
  #        {% if states.sensor.Garage_Pir.state == "motion detected" %}
  #          on
  #        {% else %}
  #          off
  #        {% endif %}
  #        {% else %}
  #        n/a
  #        {% endif %}'

automation:


  - alias: turn light led on
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.garage_pir
      to: 'motion detected'
    action:
      - service: light.turn_on
        entity_id: light.garage_led
        data:
          color_name: 'green'

  - alias: turn light led off garage
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.garage_pir
      to: 'standby'
      for:
    #    seconds: 30
        seconds: 2
    action:
      - service: light.turn_off
        entity_id: light.garage_led

  - alias: turn on water
    initial_state: True
    trigger:
      platform: state
      entity_id: input_boolean.switch_front_left_sprinklers
      to: 'off'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.switch_front_right_sprinklers
      - delay: '00:{{ states.input_number.right.state | int }}:00'
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.switch_front_right_sprinklers

