##This version of the holiday lights code does not require the node red portion
##The "W" slider under the main "holiday LED" light modifies each effect
##The "W" slider under "Glitter" light modifies the frequency of glitter, the RGB selection changes the color of the glitter
##The "W" slider under "Lightning" switch modifies the frequency of lightning.
##You must replace the ledstrip with the USER_MQTT_CLIENT_NAME you specified in the arduino USER CONFIGURATION section
homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'Holiday'
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  discovery: true
  discovery_prefix: homeassistant

sensor:
  - platform: mqtt
    name: "Current LED"
    state_topic: "ledstrip/locator"

light:
  - platform: mqtt
    schema: json
    name: "Porch led"
    state_topic: "porch/led"
    command_topic: "porch/led/set"
    optimistic: false
    retain: true
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Rainbow
      - Chase
      - Fire flicker
      - Breathe

  - platform: mqtt
    schema: json
    name: "niche Leds"
    state_topic: "torn/niche_led"
    command_topic: "torn/niche_led/set"
    retain: True
    qos: 1
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Rainbow
      - Chase
      - Fire flicker
      - Breathe


input_select:
  theater_room_effect:
    name: Theater Room Effect
    options:
     - "Christmas"
     - "Candy Cane"
     - "Holly Jolly"
     - "Valentine"
     - "Lovey Day"
     - "St Patty"
     - "Easter"
     - "USA"
     - "Independence"
     - "Go Blue"
     - "Hail"
     - "Touchdown"
     - "Halloween"
     - "Punkin"
     - "Thanksgiving"
     - "Turkey Day"
     - "BPM"
     - "Confetti"
     - "Cyclon Rainbow"
     - "Dots"
     - "Fire"
     - "Glitter"
     - "Juggle"
     - "Lightning"
     - "Police All"
     - "Police One"
     - "Rainbow"
     - "Rainbow with Glitter"
     - "Ripple"
     - "Sinelon"
     - "Solid"
     - "Twinkle"
    initial: "Solid"

input_number:
  animation_speed:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation: 
  - alias: "Theater Input Effect"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_select.theater_room_effect
    action:
      - service: mqtt.publish
        data_template:
          topic: "theater_room/seteffect"
          payload: '{{ trigger.to_state.state | string }}'

  - alias: "Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "theater_room/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'
################################
switch:
  - platform: mqtt
    name: "Front Christmas Tree"
    state_topic: "stat/ferina/POWER"
    command_topic: "stat/ferina/SET"
  #  availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bathroom heater"
    command_topic: "cmnd/bathheater/power"
    state_topic: "stat/bathheater/POWER"

  #  availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bathroom exhaust"
    command_topic: "cmnd/bathfan/power"
    state_topic: "stat/bathfan/POWER"

  #  availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bathroom led"
    command_topic: "cmnd/bathlight/power"
    state_topic: "stat/bathlight/POWER"

  #  availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
group:
  Led_porch:
    entities:
#      - automation.turn_front_lights_on_at_sunset
#      - automation.front_light_off
      - input_select.holiday
      - input_select.trash
      - switch.front_lights_switch
      - light.hyperion
      - light.front_led_lights
#      - input_select.Eave_effect
      - automation.porch_input_effect
      - input_number.porch_animation_speed
#      - automation.turn_front_led_on_at_sunset
#      - automation.front_led_off
      - light.cabinet_lights
#      - automation.turn_cabinet_on_at_sunset
#      - automation.cabinet_led_off
      - light.niche_leds
      - light.porch_led
      - light.tree_leds
      - light.canes_led
