#######################################
############## Holiday Outside Lights ######
#######################################
#mqtt:
#  broker: !secret mqtt_broker
#  port: !secret mqtt_port
#  discovery: true
#  discovery_prefix: homeassistant
#  client_id: !secret mqtt_client
#  keepalive: !secret mqtt_keepalive

light:

  - platform: mqtt
    schema: json
    name: "Front led"
    state_topic: "torn/ledlights"
    command_topic: "torn/ledlights/set"
    optimistic: false
    retain: true
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Rainbow
      - Chase
      - Fire flicker
      - Breathe
  - platform: mqtt
    schema: json
    name: "Porch led"
    state_topic: "porch/led"
    command_topic: "porch/led/set"
    optimistic: false
    retain: true
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Rainbow
      - Chase
      - Fire flicker
      - Breathe

  - platform: mqtt
    schema: json
    name: "niche Leds"
    state_topic: "torn/niche_led"
    command_topic: "torn/niche_led/set"
    retain: True
    qos: 1
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Rainbow
      - Chase
      - Fire flicker
      - Breathe
  - platform: mqtt
    schema: json
    name: "tree Leds"
    state_topic: "torn/tree"
    command_topic: "torn/tree/set"
    retain: True
    qos: 1
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Rainbow
      - Chase
      - Fire flicker
      - Breathe
  - platform: mqtt
    schema: json
    name: "canes led"
    state_topic: "torn/canes"
    command_topic: "torn/canes/set"
    retain: True
    qos: 1
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Rainbow
      - Chase
      - Fire flicker
      - Breathe
#  - platform: mqtt
#    name: "Front led"
#    command_topic: "torn/ledlights/setpower"
#    state_topic: "torn/ledlights/setpowerpub"
#    rgb_state_topic: "torn/ledlights/setcolorpub"
#    rgb_command_topic: "torn/ledlights/setcolor"
#    brightness_state_topic: "torn/ledlights/setbrightnesspub"
#    brightness_command_topic: "torn/ledlights/setbrightness"
input_number:
  animation_speed:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

  niche_speed:
    name: niche Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation:
#  - alias: "niche Animation"
#    initial_state: True
#    hide_entity: False
#    trigger:
#      - platform: state
#        entity_id: input_number.niche_speed
#    action:
#      - service: mqtt.publish
#        data_template:
#          topic: "torn/ledniche/setanimationspeed"
#          payload: '{{ trigger.to_state.state | int }}'

#  - alias: "niche Input Effect"
#    initial_state: True
#    hide_entity: False
#    trigger:
#      - platform: state
#        entity_id: input_select.niche_effect
#    action:
#      - service: mqtt.publish
#        data_template:
#          topic: "torn/ledniche/seteffect"
#          payload: '{{ trigger.to_state.state | string }}'

#  - alias: "eave Input Effect"
#    initial_state: True
#    hide_entity: False
#    trigger:
#      - platform: state
#        entity_id: input_select.eave_effect
#    action:
#      - service: mqtt.publish
#        data_template:
#          topic: "torn/ledlights/seteffect"
#          payload: '{{ trigger.to_state.state | string }}'

#  - alias: "Animation Speed"
#    initial_state: True
#    hide_entity: False
#    trigger:
#      - platform: state
#        entity_id: input_number.animation_speed
#    action:
#      - service: mqtt.publish
#        data_template:
#          topic: "torn/ledlights/setanimationspeed"
#          payload: '{{ trigger.to_state.state | int }}'

  - alias: Turn porch light On At Sunset
    initial_state: True
    hide_entity: false
    trigger:
      platform: sun
      event: sunset
      offset: '-00:00:15'
    action:
      service: switch.turn_on
      entity_id: switch.porch_light

  - alias: 'Turn porch light off at sunrise'
    initial_state: True
    trigger:
      platform: sun
      event: sunrise
  #    offset: '-07:33:00'
    action:
      service: switch.turn_off
      entity_id: switch.porch_light

  - alias: Turn eave led On At Sunset
    initial_state: True
    hide_entity: false
    trigger:
      platform: sun
      event: sunset
      offset: '00:01:00'
    action:
      service: light.turn_on
      entity_id: light.tv_color_lights

  - alias: 'front led off'
    initial_state: True
    trigger:
      platform: sun
      event: sunrise
      offset: '-00:00:30'
    action:
      service: light.turn_off
      entity_id: light.tv_color_lights

  - alias: Turn front leds On At Sunset
    initial_state: True
    hide_entity: false
    trigger:
      platform: sun
      event: sunset
    action:
      service: light.turn_on
      entity_id: light.front_led

  - alias: 'front light off'
    initial_state: True
    trigger:
      platform: sun
      event: sunrise
  #    offset: '-07:33:00'
    action:
      service: light.turn_off
      entity_id: light.front_led
switch:
  - platform: mqtt
    name: "Front Christmas Tree"
    state_topic: "stat/ferina/POWER"
    command_topic: "stat/ferina/SET"
  #  availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bathroom heater"
    command_topic: "cmnd/bathheater/power"
    state_topic: "stat/bathheater/POWER"
    
  #  availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bathroom exhaust"
    command_topic: "cmnd/bathfan/power"
    state_topic: "stat/bathfan/POWER"
    
  #  availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bathroom led"
    command_topic: "cmnd/bathlight/power"
    state_topic: "stat/bathlight/POWER"
    
  #  availability_topic: "home/bedroom/switch1/available"
    payload_on: "ON"
    payload_off: "OFF"
group:
  Led_porch:
    entities:
#      - automation.turn_front_lights_on_at_sunset
#      - automation.front_light_off
      - input_select.holiday
      - input_select.trash
      - switch.front_lights_switch
      - light.hyperion
      - light.Front_led
#      - input_select.Eave_effect
      - automation.porch_input_effect
      - input_number.porch_animation_speed
#      - automation.turn_front_led_on_at_sunset
#      - automation.front_led_off
      - light.cabinet_lights
#      - automation.turn_cabinet_on_at_sunset
#      - automation.cabinet_led_off
      - light.niche_leds
      - light.porch_led
      - light.tree_leds
      - light.canes_led

#  holiday_lights:
#    control: hidden
#    view: yes
#    icon: mdi:led-on
#    name: holiday Porch
#    entities:
#      - group.holiday_porch



################################
