light:
  - platform: mqtt
    name: "Theater Motion ws2812"
    command_topic: "cmnd/theater_room/power"
    state_topic: "stat/theater_room/POWER"
    rgb_state_topic: "stat/theater_room/color"
    rgb_command_topic: "cmnd/theater_room/color"
    brightness_state_topic: "stat/theater_room/dimmer"
    brightness_command_topic: "cmnd/theater_room/dimmer"
    retain: true

#PIR entries:
binary_sensor:
  - platform: mqtt
    state_topic: "mypir/state"
    name: "theater_room PIR"
sensor:
  - platform: mqtt
    state_topic: "tele/theater_room/SENSOR"
    name: "Theater Room Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.DHT11.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "tele/theater_room/SENSOR"
    name: "Theater Room Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.DHT11.heatIndex | round(1) }}'

  - platform: mqtt
    state_topic: "tele/theater_room/SENSOR"
    name: "Theater Room Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.DHT11.humidity | round(1) }}'
#customize:
#  binary_sensor.TR_pir:
#    device_class: motion

automation:
  - alias: 'D1 motion ON'
    trigger:
      - platform: state
        entity_id: binary_sensor.theater_room_motion
        from: 'off'
        to: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.theater_leds
#----------------------------------------------------
  - alias: 'D1 motion OFF'
    trigger:
      - platform: state
        entity_id: binary_sensor.theater_room_motion
        from: 'on'
        to: 'off'
        for: '00:01:00'
    action:
      - service: light.turn_off
        data:
          entity_id: light.theater_leds
