
climate:
  - platform: generic_thermostat
    name: Hallway Nest 
    heater: climate.hallway #fan.game_room_fan
    target_sensor: sensor.jasmin_room_temperature_2
    ac_mode: True
    target_temp: 73
    initial_hvac_mode: "off"
    cold_tolerance: 3
    hot_tolerance: -3
    
# Extract the set temperature from the generic thermostat from the office
 

  
  

automation:


  - alias: '01 jasmin temp above 79'
    trigger:
      - platform: numeric_state
        entity_id: sensor.jasmin_room_temperature_2
        above: 78
    action:
      service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: 75
        operation_mode: Cool
  - alias: '01 jasmin temp below 75'
    trigger:
      - platform: numeric_state
        entity_id: sensor.jasmin_room_temperature_2
        below: 76
    action:
      service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: 78
        operation_mode: Cool