###############################################################################
#   @user           :
#   original Github
#   https://github.com/torn8o/Home-AssistantConfig
#   @author         :   torn8o
#   @date           :   04/21/2017
#   @package        :   ios plug and play
#   @description    :   Example to understand Actionable Notifications for IOS
# htis is a package file inorder for this to work in your setup
# you must have packagesset up in your configuration.
#    To set up packages place the following line into the configuation file under
#    customize please view below order. You will then need to make a folder in the
#    .homeassistant folder called poackages.
#
#homeassistant:
#  name: your ha name
#  latitude: !secret home_latitude
#  longitude: !secret home_longitude
#  elevation: !secret home_elevation
#  time_zone: America/Chicago
#  unit_system: imperial
#  customize: !include customize.yaml
#  packages: !include_dir_named packages
###############################################################################


homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'ios plug in play'

ios:
  push:
    categories:
      - name: Trash Recycle
        identifier: 'trash_recycle'
        actions:
          - identifier: 'TRASH_LEFT'
            title: 'Done'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'TRASH_REMIND_LATER'
            title: 'Remind Later'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
      - name: live
        identifier: 'live_feed'
        actions:
          - identifier: 'SHOW_FEED'
            title: 'watch live'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
      - name: pool
        identifier: 'pool_feed'
        actions:
          - identifier: 'POOL'
            title: 'Pool Live'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'



      - name: Medicine
        identifier: 'TABLET'
        actions:
          - identifier: 'TABLET_TAKEN'
            title: 'Tablet Taken'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'REMIND_LATER'
            title: 'Remind me later'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no

      - name: garage1
        identifier: 'garage1'
        actions:
          - identifier: 'CLOSE_JANIS'
            title: 'Close Garage Door'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'REMIND_LATER'
            title: 'Remind me later'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no

      - name: Garage test
        identifier: 'Garage'
        actions:
          - identifier: 'garage'
            title: 'Reminder Garage'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

      - name: alarm
        identifier: 'alarm'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes #no
            behavior: 'default' #'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'

group: # will add a view on the main tab of home assistant
  ios_test:
    name: ios_test
    icon: mdi:apple-ios
    entities:
      - automation.Notify_iOS_Actionable_Notifications
      - automation.sound_the_alarm
      - automation.SILENCE_ALARM
      - automation.Notify_camera_Actionable_Notifications
      - automation.notify_door
      - automation.close_garage
      - automation.reset_relays
      - group.zones
notify:
    name: ios_devices
    platform: group
    services:
      - service: ios_torn8o
      - service: ios_liz
      - service: ios_ferina

automation:
  - alias: 01 Notify iOS front feed #creates the notification
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.front_door_motion
      to: 'motion'  #change this to actual trigger
    action:
      - service: notify.ios_devices
        data_template:
          title: "Front door motion" #customizable
          message: "{{ states. sensor.date__time.state }}" #customizable
          data:
            attachment:
              url: http://tornhome.ddns.net:84/mjpg/fdb #"http://tornhome.ddns.net:8123/local/front_door.jpg"
              content-type: jpg
              hide-thumbnail: false
            push:
              badge: 0 # this will remove the badge/app icon number
              category: 'live_feed' #name matched in ios component

  - alias: iOS app notification front live feed #creates the action button
    initial_state: True
  #    hide_entity: True
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SHOW_FEED #name matched in ios component
    action:

      service: notify.ios_devices
      data_template:
        message: "Front door Feed"
        data:
          push:
            category: camera
          entity_id: camera.front_door_stream
          attachment:
            url: http://tornhome.ddns.net:84/mjpg/fdb
            content-type: jpg
            hide-thumbnail: false

  - alias: 01 Notify iOS pool feed #creates the notification
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.pool_door_motion
      to: 'motion'  #change this to actual trigger
    action:
  #    - delay: '00:00:03'
      - service: notify.ios_devices
    #  service: notify.ios_torn8o #id of your ios device, might not show up until you've loaded the ios component in HA

        data:
          title: "pool motion" #customizable
          message: "{{ states. sensor.date__time.state }}" #customizable
          data:
            attachment:
              url: "{{ states.camera.pool_camera.attributes.entity_picture }}" #
              content-type: jpg
              hide-thumbnail: false
#       data:
            push:
              badge: 0 # this will remove the badge/app icon number
              category: 'pool_feed' #name matched in ios component

  - alias: iOS app notification pool live feed #creates the action button
    initial_state: True
  #    hide_entity: True
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: POOL #name matched in ios component
    action:

      service: notify.ios_devices
      data_template:
        message: "Pool Feed"
        data:
          push:
            category: camera
          entity_id: camera.pool_stream
          attachment:
            url: !secret pool_url
            content-type: jpg
            hide-thumbnail: false


  - alias: Sound the alarm
    initial_state: True
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SOUND_ALARM
    action:
      service: notify.ios_devices #change to your ios device name
      data:
        message: "window for sound of alarm"
        data:
          push:
            badge: 0
            sound: US-EN-Daisy-Back-Door-Open.wav

  - alias: silence alarm
    initial_state: True
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: SILENCE_ALARM
    action:
      service: notify.ios_devices #change to your ios device name
      data:
        message: "window for silence alarm"
        data:
          push:
            badge: 0
            sound: US-EN-Alexa-Motion-At-Back-Door.wav

  - alias: Notify iOS Garage #creates the notification
    initial_state: True
    trigger:
      - platform: time
        at: '22:00:00' #change this to actual trigger
    condition:
      condition: state
      entity_id: sensor.garage_door_status #id of your garage door relay
      state: Open
    action:
        service: notify.ios_devices #id of your ios device, might not show up until you've loaded the ios component in HA
        data:
          title: "Garage Check" #customizable
          message: "It's 10pm Garage is Open" #customizable
          data:
            push:
              badge: 0 # this will remove the badge/app icon number
              category: 'garage1' #name matched in ios component

  - alias: iOS app notification garage #creates the action button
    initial_state: True
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: CLOSE_JANIS #name matched in ios component
    action:
      service: switch.turn_on
      entity_id: switch.garage_door_opener_switch

  - alias: iOS app notification garage opened #creates the action button
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.garage_door_status
      from: 'Closed'
      to: 'Open'
    action:
        service: notify.ios_devices #id of your ios device, might not show up until you've loaded the ios component in HA
        data:
          title: "Garage Check" #customizable
          message: "Garage door opened" #customizable
          data:
            push:
              sound: "US-EN-Daisy-Garage-Door-Open.wav"
              badge: 0 # this will remove the badge/app icon number
              category: 'garage1'

  - alias: iOS app notification garage closed #creates the action button
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.garage_door_status
      from: 'Open'
      to: 'Closed'
    action:
        service: notify.ios_devices #id of your ios device, might not show up until you've loaded the ios component in HA
        data:
          title: "Garage Check" #customizable
          message: "Garage Door Has Closed" #customizable
          data:
            push:
              sound: "US-EN-Morgan-Freeman-Garage-Door-Closed.wav"
              badge: 0 # this will remove the badge/app icon number
              category: 'garage1'

