#  modified version of https://github.com/brahmafear/hass_config/blob/master/yaml/packages/ip_devices.yaml
#  added automations from https://github.com/Norien/Home-Assistant-Config/blob/master/packages/device_status.yaml
#
#
#
#
#
homeassistant:
  customize:
    device_tracker.torntravel_wireless:
      hidden: true
    device_tracker.torntravel_wired:
      hidden: true
    device_tracker.living_room_echo:
      hidden: true
    device_tracker.master_bedroom_echo:
      hidden: true
    device_tracker.game_room_echo:
      hidden: true
    device_tracker.kitchen_echo:
      hidden: true
    device_tracker.attic_esp:
      hidden: true
    device_tracker.esp_counter_lights:
      hidden: true
    device_tracker.holiday_lights_esp:
      hidden: true
    device_tracker.game_room_esp:
      hidden: true
    device_tracker.esp_living_room:
      hidden: true
    device_tracker.master_bedroom_esp:
      hidden: true

sensor:
  - platform: template
    sensors:
      torntravel_wireless:
        friendly_name: 'torntravel_wireless'
        value_template: "{{ 'Online' if is_state('device_tracker.torntravel_wireless', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.torntravel_wireless', 'home') else 'mdi:alert-circle' }}"
      torntravel_wired:
        friendly_name: 'torntravel_wired'
        value_template: "{{ 'Online' if is_state('device_tracker.torntravel_wired', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.torntravel_wired', 'home') else 'mdi:alert-circle' }}"
      esp_holiday_lights:
        friendly_name: 'esp holiday lights'
        value_template: "{{ 'Online' if is_state('device_tracker.holiday_lights_esp', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.holiday_lights_esp', 'home') else 'mdi:alert-circle' }}"
      echo_master_bedroom:
        friendly_name: 'echo master bedroom'
        value_template: "{{ 'Online' if is_state('device_tracker.master_bedroom_echo', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.master_bedroom_echo', 'home') else 'mdi:alert-circle' }}"
      echo_living_room:
        friendly_name: 'echo living room'
        value_template: "{{ 'Online' if is_state('device_tracker.living_room_echo', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.living_room_echo', 'home') else 'mdi:alert-circle' }}"
      echo_game_room:
        friendly_name: 'echo game room'
        value_template: "{{ 'Online' if is_state('device_tracker.game_room_echo', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.game_room_echo', 'home') else 'mdi:alert-circle' }}"
      echo_kitchen:
        friendly_name: 'echo kitchen'
        value_template: "{{ 'Online' if is_state('device_tracker.kitchen_echo', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.kitchen_echo', 'home') else 'mdi:alert-circle' }}"
      esp_master_bedroom:
        friendly_name: 'esp master bedroom'
        value_template: "{{ 'Online' if is_state('device_tracker.master_bedroom_esp', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.master_bedroom_esp', 'home') else 'mdi:alert-circle' }}"

      esp_attic:
        friendly_name: 'esp attic'
        value_template: "{{ 'Online' if is_state('device_tracker.Attic_esp', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.Attic_esp', 'home') else 'mdi:alert-circle' }}"
      esp_game_room:
        friendly_name: 'esp game room'
        value_template: "{{ 'Online' if is_state('device_tracker.game_room_esp', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.game_room_esp', 'home') else 'mdi:alert-circle' }}"
      esp_living_room:
        friendly_name: 'esp living room'
        value_template: "{{ 'Online' if is_state('device_tracker.esp_living_room', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.esp_living_room', 'home') else 'mdi:alert-circle' }}"
      esp_counter_lights:
        friendly_name: 'esp counter lights'
        value_template: "{{ 'Online' if is_state('device_tracker.esp_counter_lights', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:check-circle-outline' if is_state('device_tracker.esp_counter_lights', 'home') else 'mdi:alert-circle' }}"

group:
  network_devices:
    name: Network Devices
    entities:
      - sensor.esp_front_led
#      - sensor.torntravel_wireless
#      - sensor.torntravel_wired
      - sensor.esp_master_bedroom
      - sensor.esp_attic
      - sensor.esp_game_room
      - sensor.esp_holiday_lights
#      - sensor.esp_counter_lights
      - sensor.echo_living_room
      - sensor.echo_master_bedroom
      - sensor.echo_game_room
      - sensor.echo_kitchen
      - automation.Notify_if_Device_Goes_Offline

  network_views:
    name: network_views
    view: yes
    entities:
      - group.network_devices

automation:
###############################################################################
# Notify when a device goes Offline or Online
###############################################################################
  - alias: Notify if Device Goes Offline
    trigger:
      platform: state
      entity_id:
        - sensor.esp_front_led
  #      - sensor.torntravel_wireless
  #      - sensor.torntravel_wired
  #      - sensor.esp_master_bedroom
  #      - sensor.esp_attic
  #      - sensor.esp_game_room
  #      - sensor.esp_living_room
  #      - sensor.esp_counter_lights
  #      - sensor.echo_living_room
  #      - sensor.echo_master_bedroom
  #      - sensor.echo_game_room
  #      - sensor.echo_kitchen
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: notify.ios_torn8o
        data_template:
          message: >
            {% if trigger.to_state.state | lower == "offline" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
