#  modified version of https://github.com/brahmafear/hass_config/blob/master/yaml/packages/ip_devices.yaml
#  added automations from https://github.com/Norien/Home-Assistant-Config/blob/master/packages/device_status.yaml
#
#
#
#
#
homeassistant:
  customize:
    device_tracker.torntravel_wireless:
      hidden: true
    device_tracker.torntravel_wired:
      hidden: true
    device_tracker.living_room_echo:
      hidden: true
    device_tracker.master_bedroom_echo:
      hidden: true
    device_tracker.game_room_echo:
      hidden: true
    device_tracker.kitchen_echo:
      hidden: true
    device_tracker.attic_esp:
      hidden: true
    device_tracker.esp_counter_lights:
      hidden: true
    device_tracker.holiday_lights_esp:
      hidden: true
    device_tracker.game_room_esp:
      hidden: true
    device_tracker.esp_living_room:
      hidden: true
    device_tracker.master_bedroom_esp:
      hidden: true

sensor:
  - platform: template
    sensors:
      torntravel_wireless:
        friendly_name: 'torntravel_wireless'
        value_template: "{{ 'Online' if is_state('device_tracker.torntravel_wireless', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.torntravel_wireless', 'home') else 'mdi:wifi-off' }}"
      torntravel_wired:
        friendly_name: 'torntravel_wired'
        value_template: "{{ 'Online' if is_state('device_tracker.torntravel_wired', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.torntravel_wired', 'home') else 'mdi:wifi-off' }}"
      echo_master_bedroom:
        friendly_name: 'Echo Master Bedroom'
        value_template: "{{ 'Online' if is_state('device_tracker.master_bedroom_echo', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.master_bedroom_echo', 'home') else 'mdi:wifi-off' }}"
      echo_living_room:
        friendly_name: 'Echo Living Room'
        value_template: "{{ 'Online' if is_state('device_tracker.living_room_echo', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.living_room_echo', 'home') else 'mdi:wifi-off' }}"
      echo_game_room:
        friendly_name: 'Echo Game Room'
        value_template: "{{ 'Online' if is_state('device_tracker.game_room_echo', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.game_room_echo', 'home') else 'mdi:wifi-off' }}"
      echo_kitchen:
        friendly_name: 'Echo Kitchen'
        value_template: "{{ 'Online' if is_state('device_tracker.kitchen_echo', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.kitchen_echo', 'home') else 'mdi:wifi-off' }}"
      esp_front_led:
        friendly_name: 'ESP Front Led'
        value_template: "{{ 'Online' if is_state('device_tracker.esp_garage', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.esp_garage', 'home') else 'mdi:wifi-off' }}"
      esp_niche:
        friendly_name: 'ESP Niche'
        value_template: "{{ 'Online' if is_state('device_tracker.master_bedroom_esp', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.master_bedroom_esp', 'home') else 'mdi:wifi-off' }}"
      esp_garage:
        friendly_name: 'ESP Garage'
        value_template: "{{ 'Online' if is_state('device_tracker.esp_garage', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.esp_garage', 'home') else 'mdi:wifi-off' }}"
      esp_master_bedroom:
        friendly_name: 'Esp Master Bedroom'
        value_template: "{{ 'Online' if is_state('device_tracker.master_bedroom_esp', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.master_bedroom_esp', 'home') else 'mdi:wifi-off' }}"
      esp_center:
        friendly_name: 'ESP Center'
        value_template: "{{ 'Online' if is_state('device_tracker.esp_center', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.esp_center', 'home') else 'mdi:wifi-off' }}"
      esp_game_room:
        friendly_name: 'ESP Game Room'
        value_template: "{{ 'Online' if is_state('device_tracker.esp_game_room', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.esp_game_room', 'home') else 'mdi:wifi-off' }}"
      samsung_tv:
        friendly_name: 'Samsung Tv'
        value_template: "{{ 'Online' if is_state('device_tracker.samsung_tv', 'home') else 'away' }}"
        icon_template: "{{ 'mdi:television-classic' if is_state('device_tracker.samsung_tv', 'home') else 'mdi:television-classic-off' }}"
    #  esp_living_room:
    #    friendly_name: 'esp living room'
    #    value_template: "{{ 'Online' if is_state('device_tracker.esp_living_room', 'home') else 'Offline' }}"
    #    icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.esp_living_room', 'home') else 'mdi:wifi-off' }}"
      esp_counter_lights:
        friendly_name: 'Esp Kitchen Cabinet Lights'
        value_template: "{{ 'Online' if is_state('device_tracker.esp_counter_lights', 'home') else 'Offline' }}"
        icon_template: "{{ 'mdi:wifi' if is_state('device_tracker.esp_counter_lights', 'home') else 'mdi:wifi-off' }}"

group:
  network_devices:
    name: Network Devices
    entities:
      - sensor.esp_front_led
#      - sensor.torntravel_wireless
#      - sensor.torntravel_wired
      - sensor.esp_master_bedroom
      - sensor.esp_attic
      - sensor.esp_game_room
      - sensor.esp_holiday_lights
#      - sensor.esp_counter_lights
      - sensor.echo_living_room
      - sensor.echo_master_bedroom
      - sensor.echo_game_room
      - sensor.echo_kitchen
      - automation.Notify_if_Device_Goes_Offline

  network_views:
    name: network_views
    view: yes
    entities:
      - group.network_devices

automation:
###############################################################################
# Notify when a device goes Offline or Online
###############################################################################
  - alias: Notify if Device Goes Offline
    trigger:
      platform: state
      entity_id:
        - sensor.esp_front_led
  #      - sensor.torntravel_wireless
  #      - sensor.torntravel_wired
  #      - sensor.esp_master_bedroom
  #      - sensor.esp_attic
  #      - sensor.esp_game_room
  #      - sensor.esp_living_room
  #      - sensor.esp_counter_lights
  #      - sensor.echo_living_room
  #      - sensor.echo_master_bedroom
  #      - sensor.echo_game_room
  #      - sensor.echo_kitchen
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: notify.ios_torn8o
        data_template:
          message: >
            {% if trigger.to_state.state | lower == "offline" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
