light:
  - platform: mqtt
    name: "Jasmin Lights"
    command_topic: "theater_room/setpower"
    state_topic: "theater_room/setpowerpub"
    rgb_state_topic: "theater_room/setcolorpub"
    rgb_command_topic: "theater_room/setcolor"
    brightness_state_topic: "theater_room/setbrightnesspub"
    brightness_command_topic: "theater_room/setbrightness"
    optimistic: false
    
input_select:
  jasmin_led_effect:
    name: Jasmin LED Effect
    options:
     - "Christmas"
     - "Candy Cane"
     - "Holly Jolly"
     - "Valentine"
     - "Lovey Day"
     - "St Patty"
     - "Easter"
     - "USA"
     - "Independence"
     - "Go Blue"
     - "Hail"
     - "Touchdown"
     - "Halloween"
     - "Punkin"
     - "Thanksgiving"
     - "Turkey Day"
     - "BPM"
     - "Confetti"
     - "Cyclon Rainbow"
     - "Dots"
     - "Fire"
     - "Glitter"
     - "Juggle"
     - "Lightning"
     - "Police All"
     - "Police One"
     - "Rainbow"
     - "Rainbow with Glitter"
     - "Ripple"
     - "Sinelon"
     - "Solid"
     - "Twinkle"
    initial: "Solid"
input_number:
  animation_speed:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
  
automation:
  - alias: "jasmin LEDs"
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.jasmin_led_effect
    action: 
      - service: mqtt.publish
        data_template:
          topic: "theater_room/seteffect"
          payload: '{{ trigger.to_state.state | string }}'
  - alias: "Animation Speed"
    initial_state: True
    hide_entity: True
    trigger:
      - platform: state
        entity_id: input_number.animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "theater_room/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'