mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  discovery: true
  discovery_prefix: homeassistant
  client_id: !secret mqtt_client
  keepalive: !secret mqtt_keepalive
#  username: !secret mqtt_user
#  password: !secret mqtt_pass
  

light:
  - platform: mqtt_json
    name: "master Strip"
  #  state_topic: " bruh/porch"
    command_topic: "torn/master_light/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - solid
      - white
      - red
      - blue
      - green
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - twinkle
    brightness: true
    flash: true
    rgb: true
    retain: true
    optimistic: true
    qos: 0

  - platform: mqtt_json
    name: "Porch Strip"
  #  state_topic: " bruh/porch"
    command_topic: "bruh/porch/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - solid
      - white
      - red
      - blue
      - green
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - twinkle
    brightness: true
    flash: true
    rgb: true
    retain: true
    optimistic: true
    qos: 0
  - platform: mqtt_json
    name: "picture"
  #  state_topic: " bruh/porch"
    command_topic: "torn/test/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - solid
      - white
      - red
      - blue
      - green
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - twinkle
    brightness: true
    flash: true
    rgb: true
    retain: true
    optimistic: true
    qos: 0
  - platform: mqtt_json
    name: "light porch"
  #  state_topic: " bruh/porch"
    command_topic: "bruh/light/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - solid
      - white
      - red
      - blue
      - green
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - twinkle
    brightness: true
    flash: true
    rgb: true
    retain: true
    optimistic: true
    qos: 0

input_number:
  master_light_animation_speed:
    name: master light Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
  porch_animation_speed:
    name: Porch Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
  picture_animation_speed:
    name: Picture Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
  light_animation_speed:
    name: light Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation:
  - alias: "master light Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.master_light_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "torn/master_light/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'

  - alias: "Porch Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.porch_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/porch/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'

  - alias: "picture Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.picture_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "torn/test/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'

  - alias: "light Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.light_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/light/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
group:
  porch_lights:
    control: hidden
#    view: yes
    icon: mdi:led-on
    name: Led Porch
    entities:
      - group.Led_porch
      - group.Led_pic
      - group.light_porch
      - group.master_light


  Led_pic:
    entities:
      - light.picture
      - automation.picture_input_effect
      - input_number.picture_animation_speed

  Light_porch:
    entities:
      - light.light_porch
      - automation.light_input_effect
      - input_number.light_animation_speed
  master_Light:
    entities:
      - light.master_strip
      - automation.master_light_animation_speed
      - input_number.master_light_animation_speed
