
homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'master'

light:

  - platform: group
    name: Kitchen Leds
    entities:
      - light.kitchen_bar_lights
      - light.kitchen_light_level_2
  - platform: mqtt
    schema: json
    name: "mb led"
    state_topic: "torn/master_bed"
    command_topic: "torn/master_bed/set"
    brightness: true
    #flash: true
    rgb: true
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "david picture"
    state_topic: "stat/david/POWER"
    command_topic: "cmnd/david/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "zelda picture"
    state_topic: "stat/zelda/POWER"
    command_topic: "cmnd/zelda/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    schema: json
    name: Garage LED"
    state_topic: "torn/garage"
    command_topic: "torn/garage/set"
    brightness: true
    #flash: true
    rgb: true
    optimistic: false
    qos: 0

binary_sensor:
  - platform: mqtt
    name: "Master Bedroom PIR"
    state_topic: "torn/master_bed"
    value_template: '{{ value_json.motion }}'
    availability_topic: "tele/torn/master_bed"
    payload_on: "1"
    payload_off: "0"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: motion
  - platform: mqtt
    name: "Hallway PIR"
    state_topic: "Hallway/PIR"
    value_template: '{{ value_json.motion }}'
    availability_topic: "tele/Hallway/LWT"
    payload_on: "1"
    payload_off: "0"
    payload_available: "Online"
    payload_not_available: "Offline"
    device_class: motion






sensor:
  - platform: mqtt
    state_topic: "torn/attic"
    name: "attic temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "torn/attic"
    name: "attic humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "torn/attic"
    name: "Attic Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: mqtt
    state_topic: "torn/attic"
    name: "Garage Entry Motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/master_bed"
    name: "master bed motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/master_bed"
    name: "master bed temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "torn/master_bed"
    name: "master bed humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'


  - platform: template
    sensors:
      mb_motion_status:
        value_template: '{% if states.sensor.master_bed_motion %}
          {% if states.sensor.master_bed_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
