
homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'master'

light:
  - platform: group
    name: Kitchen Leds
    entities:
      - light.kitchen_bar_light_level
      - light.kitchen_light_level_2
      - light.kitchen_light_level
  - platform: group
    name: accent lights
    entities:
      - light.kitchen_cabinet_lights
      - light.display_light
      - light.tv_color_lights
      - light.niche_strip

  - platform: group
    name: accent interior lights
    entities:
      - light.kitchen_cabinet_lights
      - light.display_light
      - light.niche_leds
  - platform: group
    name: niche and porch lights
    entities:
      - light.niche_leds
      - light.porch_led

  - platform: mqtt
    schema: json
    name: "mb led"
    state_topic: "torn/master_bed"
    command_topic: "torn/master_bed/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

  - platform: mqtt
    schema: json
    name: "gr led"
    state_topic: "torn/games"
    command_topic: "torn/games/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "david picture"
    state_topic: "stat/david/POWER"
    command_topic: "cmnd/david/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "zelda picture"
    state_topic: "stat/zelda/POWER"
    command_topic: "cmnd/zelda/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    schema: json
    name: Garage LED"
    state_topic: "torn/garage"
    command_topic: "torn/garage/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

group:
  master_room_motion:
    entities:
      - sensor.master_bed_motion
      - sensor.mb_motion_status
      - light.mb_led
      - automation.turn_on_master_bedroom_light_when_there_is_movement
      - automation.turn_off_master_bedroom_light_when_there_is_no_movement



sensor:
  - platform: mqtt
    state_topic: "torn/attic"
    name: "attic temperature"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "torn/attic"
    name: "attic humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "torn/attic"
    name: "Attic Real Feel"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: mqtt
    state_topic: "torn/attic"
    name: "Garage Entry Motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/master_bed"
    name: "master bed motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/master_bed"
    name: "master bed temperature"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "torn/master_bed"
    name: "master bed humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "torn/games"
    name: "game motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "torn/games"
    name: "game temperature"
    unit_of_measurement: "째F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "torn/games"
    name: "game humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: template
    sensors:
      mb_motion_status:
        value_template: '{% if states.sensor.master_bed_motion %}
          {% if states.sensor.master_bed_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
  - platform: template
    sensors:
      gr_motion:
        value_template: '{% if states.sensor.game_motion %}
          {% if states.sensor.game_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'


automation:
#  - alias: master_bath_fan_timer
#    initial_state: True
#    trigger:
#      platform: state
#      entity_id: switch.master_bathroom_fan_switch
#  #    from: 'off'
#      to: 'on'
#      for:
#        minutes: 10
#    action:
#      service: switch.turn_off
#      entity_id: switch.master_bathroom_fan_switch

  - alias: Master Bedroom Motion
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.mb_motion_status
      to: 'on'
    condition:
      - condition: template
        value_template: >-
          {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
          {%- if hour >= 11 and hour  <=  22 -%}
            true
          {%- else -%}
            false
          {%- endif %}
    action:
      service: switch.turn_on
      entity_id: switch.master_bedroom_f_switch

  - alias: Turn off master bedroom light when there is no movement
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.mb_motion_status
      to: 'off'
      for:
        #minutes: 15
        seconds: 15
    condition:
      - condition: template
        value_template: >-
          {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
          {%- if hour >= 11 and hour <= 22 -%}
            true
          {%- else -%}
            false
          {%- endif %}
    action:
      service: switch.turn_off
      entity_id: switch.master_bedroom_f_switch

  - alias: Turn on led
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.mb_motion_status
      to: 'on'
    condition:
      - condition: template
        value_template: >-
          {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
          {%- if hour >= 10 and hour  <=  22 -%}
            true
          {%- else -%}
            false
          {%- endif %}
    action:
      service: light.turn_on
      entity_id: light.mb_led

  - alias: Turn off led
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.mb_motion_status
      to: 'off'
    condition:
      - condition: template
        value_template: >-
          {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
          {%- if hour >= 10 and hour <= 22 -%}
            true
          {%- else -%}
            false
          {%- endif %}
    action:
      service: light.turn_off
      entity_id: light.mb_led
#  - alias: Turn on kitchen light when there is movement
#    trigger:
#      platform: state
#      entity_id: group.kitchen_motion
#      to: 'on'
#    condition:
#      - condition: template
#        value_template: >-
#          {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
#          {%- if hour >= 10 and hour  <=  22 -%}
#            true
#          {%- else -%}
#            false
#          {%- endif %}
#    action:
#      service: light.turn_on
#      entity_id: group.kitchen_lights

#  - alias: Turn off kitchen light when there is no movement
#    trigger:
#      platform: state
#      entity_id: group.kitchen_motion
#      to: 'off'
#      for:
#        seconds: 15
#    condition:
#      - condition: template
#        value_template: >-
#          {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
#          {%- if hour >= 10 and hour <= 22 -%}
#            true
#          {%- else -%}
#            false
#          {%- endif %}
#    action:
#      service: light.turn_off
#      entity_id: group.kitchen_lights

  - alias: Turn on game room light when there is movement
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.gr_motion
      to: 'on'
    condition:
      - condition: template
        value_template: >-
          {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
          {%- if hour >= 10 and hour  <=  22 -%}
            true
          {%- else -%}
            false
          {%- endif %}
    action:
      service: switch.turn_on
      entity_id: switch.game_room_light

  - alias: Turn off game room light when there is no movement
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.gr_motion
      to: 'off'
      for:
        minutes: 10
    condition:
      - condition: template
        value_template: >-
          {%- set hour=(as_timestamp(now())|timestamp_custom("%H"))|int -%}
          {%- if hour >= 10 and hour  <=  22 -%}
            true
          {%- else -%}
            false
          {%- endif %}
    action:
      service: switch.turn_off
      entity_id: switch.game_room_light
