light:
  - platform: mqtt_json
    name: "niche Strip"
    state_topic: "torn/niche"
    command_topic: "torn/niche/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

input_number:
  niche_animation_speed:
    name: niche Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation: 
  - alias: "niche Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_slider.niche_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "torn/niche/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
          
