###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Scripts
#   @description    :   Nothing but Notification Stuff!
###############################################################################
homeassistant:
  customize:

    group.tts_announcements:
      order: 52

    # Script Stuff
    script.home_status:
      friendly_name: Home Status (Hourly Report)
    script.home_mode_away:
      friendly_name: Set Home Mode to AWAY
    script.good_night_tts:
      friendly_name: Good Night TTS Report

    script.voice_notify:
      hidden: true
    script.voice_greeting:
      hidden: true
    script.ifttt_leeo_color_change:
      hidden: true
    script.ifttt_notify:
      hidden: true
    script.notify_me:
      hidden: true



notify:
  - name: ios_devices
    platform: group
    services:
      - service: ios_torn8o
#      - service: ios_suresh
#      - service: ios_mallika
#      - service: ios_srinika
#      - service: ios_hasika

  # make sure you generate app password for your email if you have 2FA enabled!




script:

###############################################################################
# Notify Related Scripts
###############################################################################


  notify_me:
    sequence:
      - condition: state
        entity_id: input_boolean.text_alerts
        state: 'on'
      - condition: template
        value_template: '{{ message | trim != "" }}'
      - service: script.ios_devices
        data_template:
          message: "{{ message }}"



###############################################################################
# Voice Notify
# Conditions:
#   => Only Announce when people are home. Except in emergency mode!
#   => Only Announce when Music is NOT being played
###############################################################################
  voice_notify:
    sequence:
      - condition: template
        value_template: '{{ states.input_boolean.voice_notifications.state == "on" }}'
      - condition: template
        value_template: '{{ states.input_boolean.do_not_disturb.state | lower == "off" }}'
      - condition: template
        value_template: '{{ states.media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom.state == "idle" }}'
      - condition: template
        value_template: '{{ states.media_player.mpd.state != "playing" }}'
      - condition: template
        value_template: '{{ message | trim != "" }}'
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: template
        value_template: >
          {% if states.input_boolean.emergency_mode.state == "on" %}
            true
          {% else %}
            {{ states.group.all_devices.state == "home" }}
          {% endif %}
      - condition: template
        value_template: >
          {% if only_at_night | default('no', true ) == "yes" %}
            {% if states.sun.sun.state == "above_horizon" %}
              false
            {% else %}
              true
            {% endif %}
          {% else %}
            true
          {% endif %}
      - service: media_player.volume_set
        entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
        data_template:
          volume_level: >
            {% if states.input_boolean.emergency_mode.state == "on" %}
              {{ states.input_number.tts_volume_level_alert.state }}
            {% else %}
              {% if now().hour | int < 12 and now().hour | int > 6 %}
                {{ states.input_number.tts_volume_level_morning.state }}
              {% elif now().hour|int > 12 and now().hour|int < 20 %}
                {{ states.input_number.tts_volume_level_afternoon.state }}
              {% else %}
                {{ states.input_number.tts_volume_level_evening.state }}
              {% endif %}
            {% endif %}
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          cache: true
          message: >
            {% set msg = "" %}
            {% macro getGreeting() %}
              {% if greeting | default('yes', true ) == "yes" %}
                {% if now().hour|int < 12 %}
                  Good morning.
                {% elif now().hour|int < 18 %}
                  Good afternoon.
                {% else %}
                  Good evening.
                {% endif %}
              {% endif %}
            {% endmacro %}
            {%- macro getEndGreeting() -%}
              {%- if greeting |default('yes', true ) == "yes" -%}
                Thank you!
              {%- endif -%}
            {%- endmacro -%}
            {% set msg = msg + "<speak> " %}
            {% set msg = msg + getGreeting() %}
            {% set msg = msg + ". " + message %}
            {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
            {% set msg = msg + " " + getEndGreeting() %}
            {% set msg = msg + " </speak>" %}
            {{ msg }}

###############################################################################
# Greeting
###############################################################################
  voice_greeting:
    sequence:
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.living_room, media_player.kitchen, media_player.game_room, media_player.master_bedroom
          cache: true
          message: >
            {% set msg = "" %}
            {% macro getGreeting() %}
              {% if greeting | default('yes', true ) == "yes" %}
                {% if now().hour|int < 12 %}
                  Good morning.
                {% elif now().hour|int < 18 %}
                  Good afternoon.
                {% else %}
                  Good evening.
                {% endif %}
              {% endif %}
            {% endmacro %}
            {% set msg = msg + "<speak> " %}
            {% set msg = msg + " " + getGreeting() %}
            {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
            {% set msg = msg + " </speak>" %}
            {{ msg }}

###############################################################################
# Status around the house
###############################################################################
