homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'room_motion'

group:
  game_room_motion:
    entities:
      - camera.camera
      - sensor.game_motion
      - sensor.gr_motion_status
      - light.gr_led
      - automation.turn_on_game_room_light_when_there_is_movement
      - automation.turn_off_game_room_light_when_there_is_no_movement
  
  tautulli:
  #  name: Tautulli
    entities:
      - sensor.tautulli_total
      - sensor.tautulli_transcode
      - sensor.tautulli_direct_play
      - sensor.tautulli_direct_stream
      - sensor.tautulli_total_bandwidth
        
  porch_room_motion:
    entities:
      - sensor.front_p_motion
      - sensor.fd_motion_status
      - automation.binary_turn_on_color_light
      - automation.binary_turn_off_color_lights


  motion:
    name: room motion
  #  view: yes
    icon: mdi:walk
    entities:
      - group.game_room_motion
      - group.master_room_motion
#      - group.porch_room_motion


sensor:

  - platform: tautulli
    host: !secret tautulli_host
    ssl: false
    verify_ssl: true
    token: !secret tautulli_token
    monitored_conditions:
      - stream_count
      - stream_count_transcode
      - stream_count_direct_play
      - stream_count_direct_stream
      - total_bandwidth

  - platform: template
    sensors:
      gr_motion_status:
        value_template: '{% if states.sensor.game_motion %}
          {% if states.sensor.game_motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

#  - platform: template
#    sensors:
#      attic_motion_status:
#        value_template: '{% if states.sensor.attic_motion %}
#          {% if states.sensor.attic_motion.state == "1" %}
#            on
#          {% else %}
#            off
#          {% endif %}
#          {% else %}
#          n/a
#          {% endif %}'
  - platform: template
    sensors:
      dining_motion_status:
        value_template: '{% if states.sensor.Garage_Entry_Motion %}
          {% if states.sensor.Garage_Entry_Motion.state == "motion detected" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      kit_motion_status:
        value_template: '{% if states.sensor.kitchen_multi_sensor_burglar %}
          {% if states.sensor.kitchen_multi_sensor_burglar.state == "8" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

  - platform: template
    sensors:
      garage_motion_status:
        value_template: '{% if states.sensor.aeotec_zw100_multisensor_6_burglar %}
          {% if states.sensor.aeotec_zw100_multisensor_6_burglar.state == "8" %}
            on
          {% else %}
            off
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
