################################################################
## Packages / ISS
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'Sensor'


    ################################################
    ## Node Anchors
    ################################################
sensor:
  - platform: youtube
    channel_id: UCeAXVwwurpvQVJozU1GipTg
  - platform: tautulli
    api_key: !secret tautulli_api_key
    host: !secret tautulli_host
    ssl: false
    verify_ssl: true
#    token: !secret tautulli_token
    monitored_conditions:
      - stream_count
      - stream_count_transcode
      - stream_count_direct_play
      - stream_count_direct_stream
      - total_bandwidth


  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_api_key
    host: 192.168.1.47
#    monitored_conditions:
#      - upcoming
    days: 3
  - platform: radarr_upcoming_media
    api_key: !secret radarr_api_key
    host: 192.168.1.47
#    monitored_conditions:
#      - upcoming
    days: 14



  - platform: pollen
    zip_code: !secret home_zip
    monitored_conditions:
      - allergy_average_forecasted
      - allergy_average_historical
      - allergy_index_today
      - allergy_index_tomorrow
      - allergy_index_yesterday
      - asthma_average_forecasted
      - asthma_average_historical
      - asthma_index_today
      - asthma_index_tomorrow
      - asthma_index_yesterday
      - disease_average_forecasted


  - platform: template
    sensors:
      pollen_level:
        friendly_name: 'Pollen Level'
        value_template: >-
          {{ state_attr('sensor.allergy_index_forecasted_average', 'rating') }}
        entity_picture_template: >-
          {{ '/local/icons/' ~ state_attr('sensor.allergy_index_forecasted_average', 'rating').lower().replace('/', '-') ~ '.png'}}
      cold_flu_risk:
        friendly_name: 'Cold & Flu Risk'
        value_template: >-
          {{ state_attr('sensor.cold_flu_forecasted_average', 'rating') }}
        entity_picture_template: >-
          {{ '/local/icons/' ~ state_attr('sensor.cold_flu_forecasted_average', 'rating').lower().replace('/', '-') ~ '.png'}}
  - platform: mqtt
    name: "charlie charging"
    state_topic: "hass/state/charlie"

  - platform: mqtt
    name: "liz charging"
    state_topic: "hass/state/liz"
## Trackers
  - platform: mqtt
    state_topic: 'monitor/Monitor_pi/3C:2E:FF:97:77:1D'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'Charlie Phone BT'

  - platform: mqtt
    state_topic: 'monitor/Monitor_pi/70:70:0D:cf:a1:e6'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'Liz Phone BT'

  - platform: mqtt
    state_topic: 'monitor/Monitor_pi/3C:2E:FF:97:77:1D/rssi'
    name: 'Charlie RSSI raw'
    unit_of_measurement: 'dBm'

  - platform: filter
    name: "Charlie RSSI"
    entity_id: sensor.charlie_rssi_raw
    filters:
      - filter: outlier
        window_size: 2
        radius: 1.0
      - filter: lowpass
        time_constant: 2
      - filter: time_simple_moving_average
        window_size: 00:01
        precision: 1
  - platform: template
    sensors:
      charlie:
        friendly_name: "Charlie"
        value_template: >-
          {% if is_state('device_tracker.tornado', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}

  - platform: template
    sensors:
      liz:
        friendly_name: "Liz"
        value_template: >-
          {% if is_state('device_tracker.lynx', 'home') %}
            Home
          {% else %}
            Away
          {% endif %}
  - platform: template
    sensors:
      liz_battery:
        unit_of_measurement: '%'
        entity_id: device_tracker.lynx
        value_template: "{{ (states.device_tracker.lynx.attributes|default).battery|default|int('unknown') }}"
        icon_template: >-
          {% set battery_level = states('sensor.lynx_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
      battery_liz:
        friendly_name: "Battery Liz"
        value_template: "{{ states.device_tracker.lynx.attributes.battery|int }}"
        icon_template: >-
          {% if is_state('sensor.liz_charging', 'Charging') %}
            mdi:battery-charging
          {% endif %}
        unit_of_measurement: "%"
        device_class: battery
      battery_charlie:
        friendly_name: "Battery charlie"
        value_template: "{{ states.device_tracker.tornado.attributes.battery|int }}"
        icon_template: >-
          {% if is_state('sensor.charlie_charging', 'Charging') %}
            mdi:battery-charging
          {% endif %}
        unit_of_measurement: "%"
        device_class: battery
  #- platform: sonarr
  #  api_key: !secret sonarr_api_key
  #  host: !secret sonarr_url
  #  port: !secret sonarr_port
  #  monitored_conditions:
  #    - diskspace
  #    - upcoming
  #  days: 1
  - platform: yweather
  #  name: Weather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature

  - platform: crimereports
    name: Home crimereports
    radius: 10

  - platform: template
    sensors:
      holidays_calendar:
        friendly_name: 'Holiday'
        value_template: '{{ states.calendar.holidays_in_united_states.attributes.message }}'
  - platform: template
    sensors:
      charlie_calendar:
        friendly_name: 'Charlie'
        value_template: '{{ states.calendar.charlie_brown.attributes.message }}'

  - platform: template
    sensors:
      trash_and_recycle:
        friendly_name: 'trash_and_recycle'
        value_template: '{{ states.calendar.trash_and_recycle.attributes.message }}'
#  - platform: fastdotcom
#    minute:
#      - 0
#      - 30
  - platform: broadlink
    host: 192.168.1.7
    mac: B4:43:0D:EF:9F:25
    name: "broadlink torn"
    scan_interval: 60
    monitored_conditions:
      - temperature

  - platform: ring
  - platform: google_wifi

  - platform: mqtt
    name: "display song"
    state_topic: "xmas/falcon/player/FPP/playlist/media/status"

  - platform: mqtt
    name: 'Monitor Status'
    state_topic: 'monitor/Monitor_pi/status'

  - platform: yr
#  - platform: speedtest
#    monitored_conditions:
#    - ping
#    - download
#    - upload

  - platform: template
    sensors:
       vizio_tv:
          friendly_name: 'Vizio TV'
          value_template: "{{ 'Online' if is_state('device_tracker.vizio_tv', 'home') else 'Offline' }}"

       home_theater_status:
          friendly_name: 'Home Theater Status'
          value_template: "{{ 'Online' if is_state('media_player.denon_avr_s730h', 'on') else 'Offline' }}"

       broadlink:
          friendly_name: 'Broadlink'
          value_template: "{{ 'Online' if is_state('device_tracker.broadlink', 'home') else 'Offline' }}"

       harmony_hub:
          friendly_name: 'Harmony Hub'
          value_template: "{{ 'Online' if is_state('device_tracker.harmonyhub', 'home') else 'Offline' }}"

       tv_room:
          friendly_name: 'Tv Room'
          value_template: "{{ states.remote.torn_hub.attributes.current_activity }}"
#  - platform: command_line
#    name: Epson ink level Black
#    command: /usr/bin/curl -k https://192.168.1.166/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_K.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
#    unit_of_measurement: '%'
#    scan_interval: 14400
#  - platform: command_line
#    name: Epson Ink Level Magenta
##    command: /usr/bin/curl -k https://192.168.1.166/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_M.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  #  unit_of_measurement: '%'
  #  scan_interval: 14400
  #- platform: command_line
  #  name: Epson Ink Level Yellow
  #  command: /usr/bin/curl -k https://192.168.1.166/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_Y.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  #  unit_of_measurement: '%'
  #  scan_interval: 14400
  #- platform: command_line
  #  name: Epson Ink Level Cyan
  #  command: /usr/bin/curl -k https://192.168.1.166/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_C.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  #  unit_of_measurement: '%'
  #  scan_interval: 14400
  - platform: template
    sensors:
      kitchen_nest_battery:
        friendly_name: 'kitchen_nest_battery'
        value_template: "{{ states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level|default(-1)|int if states.binary_sensor.torn_home_kitchen_nest_protect_co_detected is not none }}"
        unit_of_measurement: '%'
        icon_template: '{% if states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.binary_sensor.torn_home_kitchen_nest_protect_co_detected.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'
  - platform: template
    sensors:
      hallway_nest_battery:
        friendly_name: 'hallway_nest_battery'
        value_template: "{{ states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level|default(-1)|int if states.binary_sensor.torn_home_hallway_nest_protect_co_detected is not none }}"
        unit_of_measurement: '%'
        icon_template: '{% if states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.binary_sensor.torn_home_hallway_nest_protect_co_detected.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'

light:
  - platform: flux_led
    devices:
      192.168.1.133:
        name: MB Color Lights
      192.168.1.28:
        name: kitchen cabinet lights
      192.168.1.127:
        name: display light
input_boolean:

    switch_bathroom_exhaust_1:
      name: bathroom exhaust 1
    switch_bathroom_heater_1:
      name: bathroom heater 1
    switch_bathroom_led_1:
      name: bathroom led 1

    disable_exterior_on_sunset:
      name: Disable Exterior Lights On at Sunset
      icon: mdi:weather-sunset-down
    interior_holiday:
      name: Interior Holiday Lighting
      icon: mdi:gift
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
speedtestdotnet:
  scan_interval:
    days: 0
    hours: 0
    minutes: 3
    seconds: 30
    milliseconds: 0
  monitored_conditions:
    - ping
    - download
    - upload
fastdotcom:
  scan_interval:
    days: 0
    hours: 0
    minutes: 3
    seconds: 30
    milliseconds: 0
## battery
binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error
  - platform: mqtt
    name: "Pool Motion"
    state_topic: blue_iris/binary_sensor/pool_motion/state
    payload_on: "ON"
    payload_off: "OFF"
    device_class: motion
  - platform: template
    sensors:
      charlie_gps_status:
        friendly_name: Charlie GPS
        device_class: connectivity
        entity_id: device_tracker.tornado
        value_template: "{{ is_state('device_tracker.tornado', 'on') }}"
        icon_template: >-
          {% if is_state('device_tracker.tornado', 'Home') %}
            mdi:crosshairs-gps
          {% elif is_state('device_tracker.tornado', 'not_home') %}
            mdi:crosshairs
          {% else %}
            mdi:alert
          {% endif %}
      charlie_ble_status:
        friendly_name: Charlie BLE
        device_class: connectivity
        entity_id: device_tracker.tornado
        value_template: "{{ is_state('device_tracker.tornado', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.tornado', 'home') %}
            mdi:bluetooth-audio
          {% elif is_state('device_tracker.tornado', 'not_home') %}
            mdi:bluetooth-audio
          {% else %}
            mdi:alert
          {% endif %}
  - platform: template
    sensors:
      liz_gps_status:
        friendly_name: Liz GPS
        device_class: connectivity
        entity_id: device_tracker.lynx
        value_template: "{{ is_state('device_tracker.lynx', 'on') }}"
        icon_template: >-
          {% if is_state('device_tracker.lynx', 'Home') %}
            mdi:crosshairs-gps
          {% elif is_state('device_tracker.lynx', 'not_home') %}
            mdi:crosshairs
          {% else %}
            mdi:alert
          {% endif %}
      liz_ble_status:
        friendly_name: Charlie BLE
        device_class: connectivity
        entity_id: device_tracker.lynx
        value_template: "{{ is_state('device_tracker.lynx', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.lynx', 'home') %}
            mdi:bluetooth-audio
          {% elif is_state('device_tracker.lynx', 'not_home') %}
            mdi:bluetooth-audio
          {% else %}
            mdi:alert
          {% endif %}
