###################################
##  Sunrise and Sunset stuff
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################
automation:
  - alias: 'Sunset Stuff on'
    trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
      from: 'above_horizon'
    action:
      - service: homeassistant.turn_on
        entity_id:
          - light.front_led_lights
          - light.porch_led
          - switch.porch_light
      - service: script.monthly_color_scene
      - service: light.turn_on
        entity_id:
          - light.porch_led
          - light.front_eave_light_color
        data_template:
          brightness: >
            {% if states.group.family.state == 'not home' -%}
            10
            {% else %}
            200
            {% endif %}
      - wait_template: >-
         {{ states.group.family.state == 'home' }}

  - alias: 'Sunset Stuff off'
    trigger:
    - platform: sun
      event: sunrise
      offset: '-02:00:00'

    action:
      - service: homeassistant.turn_off
        entity_id:
          - light.front_led_lights
          - light.porch_led
          - switch.porch_light

      - wait_template: >-
         {{ states.sun.sun.state == 'above_horizon' }}

