
homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'system'

    packages.system_hidden: &customize_hidden
      <<: *customize
      hidden: true

    automation.startup_notification:
      <<: *customize
      friendly_name: "Startup Notification"
      icon: mdi:message-text

    automation.update_notification:
      <<: *customize
      friendly_name: "Update Notification"
      icon: mdi:message-text

    binary_sensor.system_ready:
      <<: *customize_hidden
      friendly_name: "System Ready"
      icon: mdi:flag-checkered

    group.system:
      <<: *customize
      friendly_name: "System"
      icon: mdi:settings-box

    sensor.date:
      <<: *customize
      friendly_name: "System Date"
      icon: mdi:calendar

    sensor.ha_github_version:
      <<: *customize
      friendly_name: "GitHub Version"
      icon: mdi:github-box

    sensor.ha_pypi_version:
      <<: *customize
      friendly_name: "PyPi Version"
      icon: mdi:language-python

    #sensor.ha_startup_time:
    #  <<: *customize
    #  friendly_name: "Startup Time"
    #  icon: mdi:clock-start

    sensor.ha_version:
      <<: *customize
      friendly_name: "Installed Version"
      icon: mdi:settings-box

    sensor.time:
      <<: *customize
      friendly_name: "System Time"
      icon: mdi:clock

    updater.updater:
      <<: *customize
      friendly_name: "Update Available"


################################################
## Group
################################################

group:
  system:
    control: hidden
    view: yes
    icon: mdi:engine
    entities:
      - updater.updater
      - sensor.date
      - sensor.time
      - binary_sensor.system_ready
      #- sensor.ha_startup_time
      - sensor.ha_version
    #  - sensor.ha_github_version
      - sensor.ha_pypi_version

  auto:
     control: hidden
#     view: yes
     entities:
       - automation.startup_notification
       - automation.update_notification


################################################
## Automation
################################################

automation:
  - alias: startup_notification
    initial_state: 'True'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: notify.ios_devices
        data:
          message: "Home Assistant is now up and running."

  - alias: update_notification
    initial_state: True
    trigger:
      - platform: state
        entity_id: updater.updater
      - platform: homeassistant
        event: start
    condition:
      - condition: template
        value_template: >-
          {{ states('updater.updater') != 'unknown' }}
    action:
      - service: notify.ios_torn8o
        data_template:
          message: >-
            Home Assistant {{ states('updater.updater') }} is now available.

################################################
## Binary Sensor
################################################

#binary_sensor:
#  - platform: template
#    sensors:
#      system_ready:
#        entity_id: sensor.ha_startup_time
#        value_template: >-
#          {{ states('sensor.ha_startup_time') != 'unknown' }}

################################################
## Sensor
################################################

sensor:
  - platform: time_date
    display_options:
      - date
      - time

  - platform: template
    sensors:
      ha_startup_time:
        entity_id: automation.startup_notification
        value_template: >-
          {{ as_timestamp((states.automation.startup_notification.attributes|default).last_triggered|default(None))|timestamp_custom("%b %d %X") or 'unknown' }}

  - platform: rest
    name: ha_github_version
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}

  - platform: rest
    name: ha_pypi_version
    resource: 'https://pypi.python.org/pypi/homeassistant/json'
    value_template: >-
      {{ value_json.info.version }}
