homeassistant:
  customize:
    packages.system: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'theater_room'


media_player:
  - platform: denonavr
    host: 192.168.1.8
    name: denon avr s730h
# Example configuration.yaml entry
switch:
  - platform: broadlink
    mac: a0:43:b0:54:d9:23
    switches:
      - name: Curtain open
        command_on: JgBoACkMKwwQKCsMDygQJxAnKwwSJREmEScPAAR3LAssCw8oKwwQJxAnECgsCw8oECcRJhEAC1ksDCwLDygrDBAnESYQKCsMECcQJxEmEAAEdisMLAsRJywLDygQJxMkLAsQJxAoDygPAA0F
#        command_off: JgBoACgNKg0QJywMDygPKCsMDygQJxAoDygPAAR3KwwqDQ8oKwwQKA8nLAwOKQ8oECcQJxAAC1srDCsMDygqDRAnECgqDQ8oDygQJxAnEAAEdioOKg0PKA8oDygPKBAnECgPKA4pDygQAA0F
      - name: Curtain close
  #      command_off: JgBoACkMKwwQKCsMDygQJxAnKwwSJREmEScPAAR3LAssCw8oKwwQJxAnECgsCw8oECcRJhEAC1ksDCwLDygrDBAnESYQKCsMECcQJxEmEAAEdisMLAsRJywLDygQJxMkLAsQJxAoDygPAA0F
        command_on: JgBoACgNKg0QJywMDygPKCsMDygQJxAoDygPAAR3KwwqDQ8oKwwQKA8nLAwOKQ8oECcQJxAAC1srDCsMDygqDRAnECgqDQ8oDygQJxAnEAAEdioOKg0PKA8oDygPKBAnECgPKA4pDygQAA0F
      - name: Curtain Stop
        command_on: JgBoACsMKw0OKSoNDygPKA8oDygrDg4oDygPAAR4Kg4pDg4oKw0OKQ8oDygPKCsMDygPKQ8AC1wrDikNDygrDQ4oDykPKA8oKg4OKA8oEAAEdysMKw0OKQ8oDygPKBAnDygQKA8oDygPAA0F
          #    command_off: JgBoACgNKg0QJywMDygPKCsMDygQJxAoDygPAAR3KwwqDQ8oKwwQKA8nLAwOKQ8oECcQJxAAC1srDCsMDygqDRAnECgqDQ8oDygQJxAnEAAEdioOKg0PKA8oDygPKBAnECgPKA4pDygQAA0F
#switch:

sensor:
  - platform: template
    sensors:

       home_theater_status:
          friendly_name: 'Home Theater Status'
          value_template: "{{ 'Online' if is_state('media_player.denon_avr_s730h', 'on') else 'Offline' }}"
