##################################################################################
#  Written for: @torn8o
#  Fixed days trash monday and thursday ; recycle on wednesday
##################################################################################

homeassistant:
  customize:
    sensor.torn8o_recycle_day:
      friendly_name: Is it Recycle Day today?
      icon: mdi:recycle

    sensor.torn8o_trash_day:
      friendly_name: Is it Trash Day today?
      icon: mdi:delete-variant

sensor:
###################################################################################
# Recycle - Pickup is on Wednesdays.
# The sensor will check for Tuesday for a reminder a day in advance
###################################################################################
  - platform: template
    sensors:
      torn8o_recycle_day:
        value_template: >-
          {%- macro is_today_recycle_day() -%}
          {%- if as_timestamp(now())| timestamp_custom('%A', true) | lower == "tuesday" -%}
            yes
          {%- else -%}
            no
          {%- endif -%}
          {%- endmacro -%}
          {{  is_today_recycle_day()  }}

###################################################################################
# Trash - Pickup is on Mondays and Thursdays.
# The sensor will check for Sunday and Wednesday for a reminder a day in advance
###################################################################################
  - platform: template
    sensors:
      torn8o_trash_day:
        value_template: >-
          {%- macro is_today_trash_day() -%}
          {%- if (as_timestamp(now())| timestamp_custom('%A', true) | lower == "sunday") or (as_timestamp(now())| timestamp_custom('%A', true) | lower == "wednesday") -%}
            yes
          {%- else -%}
            no
          {%- endif -%}
          {%- endmacro -%}
          {{  is_today_trash_day()  }}

# #################################################################################
# #                               Automations
# #################################################################################
automation:

# #################################################################################
# #  Reminder code - Reminds 5 times every hour starting 4 PM
# #################################################################################
  - alias: Trash and Recycle Pickup Reminder
    trigger:
      - platform: time
        after: '16:00:00'
      - platform: time
        after: '17:00:00'
      - platform: time
        after: '18:00:00'
      - platform: time
        after: '19:00:00'
      - platform: time
        after: '20:00:00'
      - platform: time
        after: '21:00:00'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: sensor.torn8o_trash_day
        state: 'yes'
      - condition: state
        entity_id: sensor.torn8o_recycle_day
        state: 'yes'
    action:
      - service: script.notify_me
        data_template:
          value1: >
            {% if states.sensor.torn8o_trash_day.state == "yes" %}
              Tomorrow is the Trash Pickup day. Put the Trash bin outside, please!
            {% elif states.sensor.torn8o_recycle_day.state == "yes" %}
              Tomorrow is the Recycle Pickup day. Put the Recycle bin outside, please!
            {% endif %}
          value2: ""
