#################################################################
#                                                               #
#                   Packages/unraid                             #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.hdd_sde_temp:
      friendly_name: Parity 
      icon: mdi:harddisk
      assumed_state: false
  
    sensor.hdd_sdg_temp:
      friendly_name: Cache
      icon: mdi:harddisk
      assumed_state: false
      
    sensor.hdd_sdc_temp:
      friendly_name: Cache 2
      icon: mdi:harddisk
      assumed_state: false    
  
    sensor.hdd_sdd_temp: 
      friendly_name: Cache 3
      icon: mdi:harddisk
      assumed_state: false  
    
    sensor.hdd_sdh_temp:
      friendly_name: Cache 4
      icon: mdi:harddisk
      assumed_state: false      
      
    sensor.HDD_sdb_temp: 
      friendly_name: 3
      icon: mdi:harddisk
      assumed_state: false    
     
    sensor.hdd_sdf_temp: 
      friendly_name: 4
      icon: mdi:harddisk
      assumed_state: false
      
    ############  Unraid Hardware info  ##########
    sensor.processor_use:
      friendly_name: processor use
      homebridge_hidden: true
    
    sensor.memory_use_percent:
      friendly_name: memory use
      icon: mdi:chip
      homebridge_hidden: true
  
    sensor.last_boot:
      friendly_name: last boot
      icon: mdi:update
      homebridge_hidden: true
  
    sensor.time_online:
      friendly_name: time Online
      icon: mdi:home-assistant
      homebridge_hidden: true
      unit_of_measurement: 'שעות'  
      
    sensor.current_ha_version:
      hidden: false
      icon: mdi:new-box
      friendly_name: Ha Version
      homebridge_hidden: false
  
    sensor.installed_version:
      hidden: false
      icon: mdi:home-automation
      friendly_name: גרסא מותקנת
      homebridge_hidden: false
  
    # sensor.disk_use_percent_home:
    #   icon: mdi:harddisk
    #   homebridge_hidden: true

    sensor.ssd_usage:
      icon: mdi:harddisk
      homebridge_hidden: true  
    
    sensor.disk_use:
      friendly_name: Disk Use

    sensor.home_assistant_v2_db:
      icon: mdi:database
      homebridge_hidden: true
  
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  hdd temp:
    name: HDD Temp
    view: no
    entities:
      - sensor.hdd_sde_temp
      - sensor.hdd_sdd_temp
      - sensor.hdd_sdh_temp
      - sensor.hdd_sdb_temp
      - sensor.hdd_sdf_temp
      - sensor.hdd_sdg_temp
      - sensor.hdd_sdc_temp
  
  unraid info:
    name: unraid info
    view: no
    entities:
      - sensor.cpu_temp    
      - sensor.processor_use
      - sensor.memory_use_percent
      - sensor.home_assistant_v2_db
  
  homeassistant info:
    name: HomeAssistant info
    view: no
    entities:
      - sensor.current_ha_version
      - sensor.installed_version
      - sensor.last_boot
      - sensor.time_online      
  



#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:
  - alias: 'SSD cache usage alert'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssd_usage
      above: 80
    action:
      - service: notify.ios
        data:
          title: 'test'
          message: 'this is test'
  

   
#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 
sensor:
  ############  HDD Temp  ##########
   # Parity
  - platform: command_line
    name: 'HDD_sde_temp'
    unit_of_measurement: "°C"
    scan_interval: 120 
    command: "hddtemp -n /dev/sde"

  # Disk 1
  - platform: command_line
    name: 'HDD_sdd_temp'
    unit_of_measurement: "°C" 
    scan_interval: 120 
    command: "hddtemp -n /dev/sdd"

  # Disk 2
  - platform: command_line
    name: 'HDD_sdh_temp'
    unit_of_measurement: "°C" 
    scan_interval: 120 
    command: "hddtemp -n /dev/sdh" 

  # Disk 3
  - platform: command_line
    name: 'HDD_sdb_temp'
    unit_of_measurement: "°C" 
    scan_interval: 120 #2 min
    command: "hddtemp -n /dev/sdb"    

  # Disk 4
  - platform: command_line
    name: 'HDD_sdf_temp'
    unit_of_measurement: "°C" 
    scan_interval: 120 
    command: "hddtemp -n /dev/sdf"    

  # Cache
  - platform: command_line
    name: 'HDD_sdg_temp'
    unit_of_measurement: "°C" 
    scan_interval: 120 
    command: "hddtemp -n /dev/sdg"
  
  # Cache 2
  - platform: command_line
    name: 'HDD_sdc_temp'
    unit_of_measurement: "°C" 
    scan_interval: 120 
    command: "hddtemp -n /dev/sdc"    
 
 
    
  ############  Unraid Hardware  ##########
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
 
  ############  Database size ############   
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db

  ############  Time homeassistant activity #############
  - platform: uptime
    name: Time Online         

  ############  Processor speed ##############
  - platform: command_line
    name: 'CPU temp'
    unit_of_measurement: "°C"
    scan_interval: 120 
    command: " sshpass -p 1028 ssh -o StrictHostKeyChecking=no root@192.168.1.47 'sensors |grep CPU | grep -o '[0-9][0-9].[0-9]' | head -1;' "
 
  ############  The latest version of ha ##############
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: Current HA Version
  
  ############  The latest version of ha install ##############
  - platform: command_line
    name: Installed version
    command: "head -5 /config/.HA_VERSION"      
    

  ############  The uptime unraid ##############
  - platform: command_line
    name: uptime unraid
    command: "uptime -p"   
 
  ############  load unraid ##############
  - platform: command_line
    name: load unraid
    command: "cat /proc/loadavg"

  ############  SSD Usage  ##############
  - platform: command_line 
    command: "bash /config/bin/ssd_usage.sh"
    name: 'SSD Usage'
    unit_of_measurement: "%" #temperature in C
    scan_interval: 600 #10 min    